begin;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'enum_donation_fulfillments_status') then
    create type public.enum_donation_fulfillments_status as enum (
      'pending', 'processing', 'completed', 'action_required'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'enum_donation_fulfillments_receipt_status') then
    create type public.enum_donation_fulfillments_receipt_status as enum (
      'pending', 'stored', 'failed'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'enum_donation_fulfillments_report_status') then
    create type public.enum_donation_fulfillments_report_status as enum (
      'pending', 'created', 'failed'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'enum_donation_fulfillments_email_status') then
    create type public.enum_donation_fulfillments_email_status as enum (
      'pending', 'sent', 'failed', 'skipped'
    );
  end if;
end;
$$;

create table if not exists public.donation_fulfillments (
  id integer generated by default as identity primary key,
  donation_id integer not null references public.donations(id) on delete restrict,
  status public.enum_donation_fulfillments_status not null default 'pending',
  receipt_status public.enum_donation_fulfillments_receipt_status not null default 'pending',
  report_status public.enum_donation_fulfillments_report_status not null default 'pending',
  email_status public.enum_donation_fulfillments_email_status not null default 'pending',
  attempt_count numeric not null default 0 check (attempt_count >= 0),
  last_attempt_at timestamp(3) with time zone,
  last_error character varying,
  email_message_id character varying,
  updated_at timestamp(3) with time zone not null default now(),
  created_at timestamp(3) with time zone not null default now()
);

create unique index if not exists donation_fulfillments_donation_id_idx
  on public.donation_fulfillments (donation_id);
create index if not exists donation_fulfillments_status_updated_at_idx
  on public.donation_fulfillments (status, updated_at desc);
create index if not exists donation_fulfillments_created_at_idx
  on public.donation_fulfillments (created_at);
create index if not exists donation_fulfillments_updated_at_idx
  on public.donation_fulfillments (updated_at);

alter table public.donation_fulfillments enable row level security;
revoke all on public.donation_fulfillments from anon, authenticated;

commit;
