begin;

create table if not exists public.campaign_funding_pools (
  id integer generated by default as identity primary key,
  campaign_id integer not null references public.campaigns(id) on delete cascade,
  internal_label varchar not null,
  currency public.enum_campaigns_currency not null,
  target_amount numeric not null check (target_amount >= 0),
  collected_amount numeric not null default 0 check (collected_amount >= 0),
  donor_count numeric not null default 0 check (donor_count >= 0),
  reporting_mode public.enum_campaigns_reporting_mode not null default 'pool',
  is_donation_open boolean not null default true,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (campaign_id, currency)
);

create table if not exists public.campaign_funding_pools_locales (
  id integer generated by default as identity primary key,
  title varchar not null,
  description jsonb,
  category_id integer references public.categories(id) on delete set null,
  cover_image_alt varchar,
  _locale public._locales not null,
  _parent_id integer not null references public.campaign_funding_pools(id) on delete cascade,
  unique (_locale, _parent_id)
);

create index if not exists campaign_funding_pools_campaign_id_idx on public.campaign_funding_pools (campaign_id);
create index if not exists campaign_funding_pools_open_idx on public.campaign_funding_pools (campaign_id, is_donation_open) where is_donation_open = true;
create index if not exists campaign_funding_pools_locales_parent_id_idx on public.campaign_funding_pools_locales (_parent_id);

alter table public.donation_intents add column if not exists funding_pool_id integer references public.campaign_funding_pools(id) on delete restrict;
alter table public.donations add column if not exists funding_pool_id integer references public.campaign_funding_pools(id) on delete restrict;
create index if not exists donation_intents_funding_pool_id_idx on public.donation_intents (funding_pool_id);
create index if not exists donations_funding_pool_id_idx on public.donations (funding_pool_id);

-- Every existing single-currency campaign receives its matching first pool.
insert into public.campaign_funding_pools (campaign_id, internal_label, currency, target_amount, collected_amount, donor_count, reporting_mode, is_donation_open, created_at, updated_at)
select id, concat('Eski ', currency::text, ' havuzu'), currency, target_amount, coalesce(collected_amount, 0), coalesce(donor_count, 0), reporting_mode, coalesce(is_donation_open, true), created_at, updated_at
from public.campaigns
on conflict (campaign_id, currency) do nothing;

insert into public.campaign_funding_pools_locales (title, description, category_id, cover_image_alt, _locale, _parent_id)
select locales.title, locales.description, campaign.category_id, campaign.cover_image_alt, locales._locale, pool.id
from public.campaigns campaign
join public.campaign_funding_pools pool on pool.campaign_id = campaign.id and pool.currency = campaign.currency
join public.campaigns_locales locales on locales._parent_id = campaign.id
on conflict (_locale, _parent_id) do nothing;

update public.donation_intents intent
set funding_pool_id = pool.id
from public.campaign_funding_pools pool
where intent.funding_pool_id is null and pool.campaign_id = intent.campaign_id and pool.currency::text = intent.currency::text;

update public.donations donation
set funding_pool_id = pool.id
from public.campaign_funding_pools pool
where donation.funding_pool_id is null and pool.campaign_id = donation.campaign_id and pool.currency::text = donation.currency::text;

alter table public.payment_ledger_entries add column if not exists funding_pool_id integer references public.campaign_funding_pools(id) on delete restrict;
create index if not exists payment_ledger_entries_funding_pool_created_at_idx on public.payment_ledger_entries (funding_pool_id, created_at desc);
update public.payment_ledger_entries entry
set funding_pool_id = pool.id
from public.campaign_funding_pools pool
where entry.funding_pool_id is null and pool.campaign_id = entry.campaign_id and pool.currency::text = entry.currency;

create table if not exists public.campaign_funding_pool_financial_totals (
  funding_pool_id integer primary key references public.campaign_funding_pools(id) on delete restrict,
  currency text not null check (currency in ('TRY', 'USD', 'EUR', 'GBP')),
  captured_amount numeric(14, 2) not null default 0 check (captured_amount >= 0),
  refunded_amount numeric(14, 2) not null default 0 check (refunded_amount >= 0),
  net_confirmed_amount numeric(14, 2) not null default 0 check (net_confirmed_amount >= 0),
  donor_count integer not null default 0 check (donor_count >= 0),
  updated_at timestamptz not null default now()
);

alter table public.campaign_funding_pools enable row level security;
alter table public.campaign_funding_pools_locales enable row level security;
alter table public.campaign_funding_pool_financial_totals enable row level security;

commit;

begin;

create or replace function public.record_funding_pool_ledger_entry(
  p_donation_id integer,
  p_campaign_id integer,
  p_funding_pool_id integer,
  p_refund_request_id integer,
  p_entry_type text,
  p_amount numeric,
  p_currency text,
  p_provider_reference text,
  p_idempotency_key text,
  p_remove_donor boolean default false,
  p_metadata jsonb default '{}'::jsonb
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_inserted_id bigint;
  v_pool_currency text;
  v_pool_campaign_id integer;
begin
  select currency::text, campaign_id into v_pool_currency, v_pool_campaign_id
  from public.campaign_funding_pools where id = p_funding_pool_id for update;
  if v_pool_currency is null or v_pool_campaign_id <> p_campaign_id then raise exception 'funding pool not found'; end if;
  if v_pool_currency <> p_currency then raise exception 'funding pool and ledger currencies must match'; end if;
  insert into public.payment_ledger_entries (donation_id, campaign_id, funding_pool_id, refund_request_id, entry_type, amount, currency, provider_reference, idempotency_key, metadata)
  values (p_donation_id, p_campaign_id, p_funding_pool_id, p_refund_request_id, p_entry_type, p_amount, p_currency, p_provider_reference, p_idempotency_key, coalesce(p_metadata, '{}'::jsonb))
  on conflict (idempotency_key) do nothing returning id into v_inserted_id;
  if v_inserted_id is null then return false; end if;
  insert into public.campaign_funding_pool_financial_totals (funding_pool_id, currency, captured_amount, refunded_amount, net_confirmed_amount, donor_count)
  values (p_funding_pool_id, p_currency, case when p_entry_type = 'capture' then p_amount else 0 end, case when p_entry_type in ('refund','cancel') then p_amount else 0 end, case when p_entry_type = 'capture' then p_amount else 0 end - case when p_entry_type in ('refund','cancel') then p_amount else 0 end, case when p_entry_type = 'capture' then 1 else 0 end - case when p_remove_donor then 1 else 0 end)
  on conflict (funding_pool_id) do update set captured_amount = campaign_funding_pool_financial_totals.captured_amount + excluded.captured_amount, refunded_amount = campaign_funding_pool_financial_totals.refunded_amount + excluded.refunded_amount, net_confirmed_amount = greatest(0, campaign_funding_pool_financial_totals.net_confirmed_amount + excluded.net_confirmed_amount), donor_count = greatest(0, campaign_funding_pool_financial_totals.donor_count + excluded.donor_count), updated_at = now();
  update public.campaign_funding_pools set collected_amount = totals.net_confirmed_amount, donor_count = totals.donor_count, updated_at = now() from public.campaign_funding_pool_financial_totals totals where campaign_funding_pools.id = p_funding_pool_id and totals.funding_pool_id = campaign_funding_pools.id;
  return true;
end;
$$;
revoke all on function public.record_funding_pool_ledger_entry(integer, integer, integer, integer, text, numeric, text, text, text, boolean, jsonb) from public, anon, authenticated;
grant execute on function public.record_funding_pool_ledger_entry(integer, integer, integer, integer, text, numeric, text, text, text, boolean, jsonb) to service_role;
commit;
