/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    campaigns: Campaign;
    'campaign-funding-pools': CampaignFundingPool;
    'news-categories': NewsCategory;
    news: News;
    pages: Page;
    'qurbani-seasons': QurbaniSeason;
    'qurbani-countries': QurbaniCountry;
    'qurbani-regions': QurbaniRegion;
    'qurbani-products': QurbaniProduct;
    'qurbani-stock-batches': QurbaniStockBatch;
    'qurbani-stock-batch-lines': QurbaniStockBatchLine;
    'qurbani-price-revisions': QurbaniPriceRevision;
    'qurbani-pools': QurbaniPool;
    'qurbani-checkouts': QurbaniCheckout;
    'qurbani-checkout-lines': QurbaniCheckoutLine;
    'qurbani-inventory-holds': QurbaniInventoryHold;
    'qurbani-orders': QurbaniOrder;
    'qurbani-shares': QurbaniShare;
    'qurbani-allocations': QurbaniAllocation;
    'qurbani-field-packages': QurbaniFieldPackage;
    'qurbani-field-package-items': QurbaniFieldPackageItem;
    'qurbani-documents': QurbaniDocument;
    'qurbani-videos': QurbaniVideo;
    'qurbani-access-links': QurbaniAccessLink;
    'qurbani-messages': QurbaniMessage;
    'qurbani-jobs': QurbaniJob;
    'donation-intents': DonationIntent;
    'payment-sessions': PaymentSession;
    'panel-settings': PanelSetting;
    'payment-events': PaymentEvent;
    donations: Donation;
    'donation-fulfillments': DonationFulfillment;
    'refund-requests': RefundRequest;
    'field-tasks': FieldTask;
    'proof-submissions': ProofSubmission;
    'proof-assets': ProofAsset;
    'donor-reports': DonorReport;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    campaigns: CampaignsSelect<false> | CampaignsSelect<true>;
    'campaign-funding-pools': CampaignFundingPoolsSelect<false> | CampaignFundingPoolsSelect<true>;
    'news-categories': NewsCategoriesSelect<false> | NewsCategoriesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'qurbani-seasons': QurbaniSeasonsSelect<false> | QurbaniSeasonsSelect<true>;
    'qurbani-countries': QurbaniCountriesSelect<false> | QurbaniCountriesSelect<true>;
    'qurbani-regions': QurbaniRegionsSelect<false> | QurbaniRegionsSelect<true>;
    'qurbani-products': QurbaniProductsSelect<false> | QurbaniProductsSelect<true>;
    'qurbani-stock-batches': QurbaniStockBatchesSelect<false> | QurbaniStockBatchesSelect<true>;
    'qurbani-stock-batch-lines': QurbaniStockBatchLinesSelect<false> | QurbaniStockBatchLinesSelect<true>;
    'qurbani-price-revisions': QurbaniPriceRevisionsSelect<false> | QurbaniPriceRevisionsSelect<true>;
    'qurbani-pools': QurbaniPoolsSelect<false> | QurbaniPoolsSelect<true>;
    'qurbani-checkouts': QurbaniCheckoutsSelect<false> | QurbaniCheckoutsSelect<true>;
    'qurbani-checkout-lines': QurbaniCheckoutLinesSelect<false> | QurbaniCheckoutLinesSelect<true>;
    'qurbani-inventory-holds': QurbaniInventoryHoldsSelect<false> | QurbaniInventoryHoldsSelect<true>;
    'qurbani-orders': QurbaniOrdersSelect<false> | QurbaniOrdersSelect<true>;
    'qurbani-shares': QurbaniSharesSelect<false> | QurbaniSharesSelect<true>;
    'qurbani-allocations': QurbaniAllocationsSelect<false> | QurbaniAllocationsSelect<true>;
    'qurbani-field-packages': QurbaniFieldPackagesSelect<false> | QurbaniFieldPackagesSelect<true>;
    'qurbani-field-package-items': QurbaniFieldPackageItemsSelect<false> | QurbaniFieldPackageItemsSelect<true>;
    'qurbani-documents': QurbaniDocumentsSelect<false> | QurbaniDocumentsSelect<true>;
    'qurbani-videos': QurbaniVideosSelect<false> | QurbaniVideosSelect<true>;
    'qurbani-access-links': QurbaniAccessLinksSelect<false> | QurbaniAccessLinksSelect<true>;
    'qurbani-messages': QurbaniMessagesSelect<false> | QurbaniMessagesSelect<true>;
    'qurbani-jobs': QurbaniJobsSelect<false> | QurbaniJobsSelect<true>;
    'donation-intents': DonationIntentsSelect<false> | DonationIntentsSelect<true>;
    'payment-sessions': PaymentSessionsSelect<false> | PaymentSessionsSelect<true>;
    'panel-settings': PanelSettingsSelect<false> | PanelSettingsSelect<true>;
    'payment-events': PaymentEventsSelect<false> | PaymentEventsSelect<true>;
    donations: DonationsSelect<false> | DonationsSelect<true>;
    'donation-fulfillments': DonationFulfillmentsSelect<false> | DonationFulfillmentsSelect<true>;
    'refund-requests': RefundRequestsSelect<false> | RefundRequestsSelect<true>;
    'field-tasks': FieldTasksSelect<false> | FieldTasksSelect<true>;
    'proof-submissions': ProofSubmissionsSelect<false> | ProofSubmissionsSelect<true>;
    'proof-assets': ProofAssetsSelect<false> | ProofAssetsSelect<true>;
    'donor-reports': DonorReportsSelect<false> | DonorReportsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('tr' | 'en' | 'ar') | ('tr' | 'en' | 'ar')[];
  globals: {};
  globalsSelect: {};
  locale: 'tr' | 'en' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'super_admin' | 'finance' | 'field_operator' | 'approver';
  isActive?: boolean | null;
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Material Symbols icon name (e.g. "favorite", "volunteer_activism")
   */
  icon?: string | null;
  /**
   * Hex color code (e.g. #10B981)
   */
  color?: string | null;
  slug: string;
  sortOrder?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns".
 */
export interface Campaign {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  targetAmount: number;
  collectedAmount?: number | null;
  coverImagePath?: string | null;
  coverImageAlt?: string | null;
  code: string;
  image?: (number | null) | Media;
  category?: (number | null) | Category;
  currency?: ('TRY' | 'USD' | 'EUR' | 'GBP') | null;
  reportingMode?: ('pool' | 'donation_based') | null;
  isDonationOpen?: boolean | null;
  slug: string;
  donorCount?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaign-funding-pools".
 */
export interface CampaignFundingPool {
  id: number;
  campaign: number | Campaign;
  internalLabel: string;
  currency: 'TRY' | 'USD' | 'EUR' | 'GBP';
  targetAmount: number;
  collectedAmount?: number | null;
  donorCount?: number | null;
  reportingMode?: ('pool' | 'donation_based') | null;
  isDonationOpen?: boolean | null;
  availableLocales:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: (number | null) | Category;
  coverImageAlt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-categories".
 */
export interface NewsCategory {
  id: number;
  name: string;
  description?: string | null;
  slug: string;
  sortOrder?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  category?: ('haber' | 'etkinlik' | 'duyuru' | 'proje') | null;
  newsCategory?: (number | null) | NewsCategory;
  availableLocales:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  excerpt?: string | null;
  contentBlocks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  searchText?: string | null;
  readTimeMinutes?: number | null;
  coverImagePath?: string | null;
  coverImageAlt?: string | null;
  relatedCampaigns?: (number | Campaign)[] | null;
  status: 'draft' | 'published' | 'archived';
  featured?: boolean | null;
  sortOrder?: number | null;
  viewCount?: number | null;
  publishedAt?: string | null;
  slug: string;
  author?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  slug: string;
  published?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-seasons".
 */
export interface QurbaniSeason {
  id: number;
  year: number;
  status: 'draft' | 'active' | 'sales_closed' | 'completed' | 'archived';
  salesStartAt: string;
  salesEndAt: string;
  eidAt: string;
  codeCounter: number;
  availableLocales:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  heroTitle: string;
  heroDescription?: string | null;
  pageContent?: string | null;
  processSteps?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  heroImage?: (number | null) | Media;
  bankName?: string | null;
  accountHolder?: string | null;
  iban?: string | null;
  bankBranch?: string | null;
  eftDescription?: string | null;
  proxyTextVersion: string;
  proxyText: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-countries".
 */
export interface QurbaniCountry {
  id: number;
  isoCode: string;
  slug: string;
  name: string;
  description?: string | null;
  image?: (number | null) | Media;
  isActive: boolean;
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-regions".
 */
export interface QurbaniRegion {
  id: number;
  season: number | QurbaniSeason;
  country: number | QurbaniCountry;
  slug: string;
  name: string;
  description?: string | null;
  publicContent?: string | null;
  image?: (number | null) | Media;
  salesStartAt: string;
  salesEndAt: string;
  fieldPreparationAt?: string | null;
  countdownAt?: string | null;
  codeCounter: number;
  isActive: boolean;
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-products".
 */
export interface QurbaniProduct {
  id: number;
  season: number | QurbaniSeason;
  country?: (number | null) | QurbaniCountry;
  regionRef?: (number | null) | QurbaniRegion;
  campaign: number | Campaign;
  fundingPool: number | CampaignFundingPool;
  title: string;
  description?: string | null;
  region: string;
  image?: (number | null) | Media;
  kind: 'cattle' | 'small_livestock';
  price: number;
  currency: 'TRY' | 'USD' | 'EUR' | 'GBP';
  capacity: number;
  salesStartAt?: string | null;
  salesEndAt?: string | null;
  sortOrder: number;
  isActive: boolean;
  currentPriceRevision?: (number | null) | QurbaniPriceRevision;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-price-revisions".
 */
export interface QurbaniPriceRevision {
  id: number;
  product: number | QurbaniProduct;
  batchLine?: (number | null) | QurbaniStockBatchLine;
  revision: number;
  unitPrice: number;
  currency: 'TRY' | 'USD' | 'EUR' | 'GBP';
  status: 'scheduled' | 'active' | 'retired';
  effectiveFrom: string;
  effectiveTo?: string | null;
  createdBy?: (number | null) | User;
  reason?: string | null;
  isLegacy: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-stock-batch-lines".
 */
export interface QurbaniStockBatchLine {
  id: number;
  batch: number | QurbaniStockBatch;
  product: number | QurbaniProduct;
  kind: 'cattle' | 'small_livestock';
  animalCount: number;
  capacity: number;
  totalQuantity: number;
  priceRevision?: (number | null) | QurbaniPriceRevision;
  status: 'draft' | 'active' | 'depleted' | 'closed' | 'cancelled';
  salesStartAt?: string | null;
  salesEndAt?: string | null;
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-stock-batches".
 */
export interface QurbaniStockBatch {
  id: number;
  season: number | QurbaniSeason;
  country: number | QurbaniCountry;
  region?: (number | null) | QurbaniRegion;
  code: string;
  name: string;
  nature: 'planned' | 'secured';
  status: 'draft' | 'active' | 'paused' | 'preparing' | 'transferred' | 'completed' | 'archived';
  idempotencyKey: string;
  animalCount: number;
  totalCapacity: number;
  availableCapacity: number;
  salesStartAt?: string | null;
  salesEndAt?: string | null;
  createdBy?: (number | null) | User;
  notes?: string | null;
  isLegacy: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-pools".
 */
export interface QurbaniPool {
  id: number;
  season: number | QurbaniSeason;
  product: number | QurbaniProduct;
  country?: (number | null) | QurbaniCountry;
  stockBatchLine?: (number | null) | QurbaniStockBatchLine;
  priceRevision?: (number | null) | QurbaniPriceRevision;
  ordinal?: number | null;
  code?: string | null;
  capacity: number;
  reservedCount: number;
  confirmedCount: number;
  status:
    'open' | 'full' | 'assigned' | 'in_progress' | 'video_processing' | 'ready' | 'notified' | 'closed' | 'withdrawn';
  fieldTask?: (number | null) | FieldTask;
  fullAt?: string | null;
  lockedAt?: string | null;
  actionRequired: boolean;
  operationNotes?: string | null;
  isLegacy: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "field-tasks".
 */
export interface FieldTask {
  id: number;
  campaign: number | Campaign;
  /**
   * Bu görev bir kurban havuzuna bağlıysa seçilir.
   */
  qurbaniPool?: (number | null) | QurbaniPool;
  title: string;
  location: string;
  assignedTo: number | User;
  dueAt?: string | null;
  status?: ('todo' | 'in_progress' | 'submitted' | 'approved' | 'needs_revision') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-checkouts".
 */
export interface QurbaniCheckout {
  id: number;
  publicId: string;
  buyerMask?: string | null;
  buyerHash?: string | null;
  encryptedPayload?: string | null;
  encryptionIv?: string | null;
  encryptionTag?: string | null;
  encryptionKeyVersion?: string | null;
  campaign: number | Campaign;
  fundingPool: number | CampaignFundingPool;
  totalAmount: number;
  currency: 'TRY' | 'USD' | 'EUR' | 'GBP';
  status:
    | 'created'
    | 'held'
    | 'payment_initialized'
    | 'payment_received_processing'
    | 'succeeded'
    | 'failed'
    | 'expired'
    | 'cancelled';
  source: 'website' | 'manual';
  providerConversationId?: string | null;
  providerPaymentId?: string | null;
  donationIntent?: (number | null) | DonationIntent;
  donation?: (number | null) | Donation;
  expiresAt: string;
  finalizedAt?: string | null;
  ipAddress?: string | null;
  failureCode?: string | null;
  piiPurgeAt: string;
  piiPurgedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-intents".
 */
export interface DonationIntent {
  id: number;
  conversationId: string;
  donorName: string;
  email: string;
  phone?: string | null;
  campaign: number | Campaign;
  fundingPool?: (number | null) | CampaignFundingPool;
  qurbaniOrder?: (number | null) | QurbaniOrder;
  qurbaniCheckout?: (number | null) | QurbaniCheckout;
  amount: number;
  currency: 'TRY' | 'USD' | 'EUR' | 'GBP';
  status?: ('draft' | 'payment_initialized' | 'callback_received' | 'completed' | 'failed') | null;
  note?: string | null;
  taxReceiptRequested?: boolean | null;
  kvkkAcceptedAt?: string | null;
  termsAcceptedAt?: string | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-orders".
 */
export interface QurbaniOrder {
  id: number;
  orderNumber: string;
  season: number | QurbaniSeason;
  product: number | QurbaniProduct;
  pool?: (number | null) | QurbaniPool;
  checkout?: (number | null) | QurbaniCheckout;
  checkoutLine?: (number | null) | QurbaniCheckoutLine;
  priceRevision?: (number | null) | QurbaniPriceRevision;
  donationIntent?: (number | null) | DonationIntent;
  donation?: (number | null) | Donation;
  buyerName: string;
  buyerEmail: string;
  buyerPhone: string;
  countryCode: string;
  identityType?: ('tc_identity' | 'passport' | 'national_identity') | null;
  identityNumber?: string | null;
  addressSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  productSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  unitPrice: number;
  shareCount: number;
  totalAmount: number;
  currency: 'TRY' | 'USD' | 'EUR' | 'GBP';
  paymentMethod: 'iyzico' | 'eft';
  reservationKind: 'iyzico' | 'eft';
  status:
    | 'reserved'
    | 'pending_payment'
    | 'pending_eft_review'
    | 'paid'
    | 'failed'
    | 'expired'
    | 'cancelled'
    | 'action_required'
    | 'refunded';
  reservedUntil: string;
  providerPaymentId?: string | null;
  providerReference?: string | null;
  eftProofBucket?: string | null;
  eftProofPath?: string | null;
  eftProofMimeType?: string | null;
  eftReviewedAt?: string | null;
  eftReviewedBy?: (number | null) | User;
  proxyTextVersion: string;
  proxyAcceptedAt: string;
  proxyAcceptedIp: string;
  phoneProxyConfirmedAt?: string | null;
  phoneProxyConfirmedBy?: (number | null) | User;
  kvkkAcceptedAt: string;
  termsAcceptedAt: string;
  thirdPartyContactConsentAt?: string | null;
  paidAt?: string | null;
  failureReason?: string | null;
  isLegacy: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-checkout-lines".
 */
export interface QurbaniCheckoutLine {
  id: number;
  checkout: number | QurbaniCheckout;
  product: number | QurbaniProduct;
  stockBatchLine: number | QurbaniStockBatchLine;
  priceRevision: number | QurbaniPriceRevision;
  quantity: number;
  participantCount: number;
  encryptedItemIndex: number;
  unitPrice: number;
  totalAmount: number;
  currency: 'TRY' | 'USD' | 'EUR' | 'GBP';
  status: 'held' | 'finalized' | 'released' | 'expired';
  order?: (number | null) | QurbaniOrder;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations".
 */
export interface Donation {
  id: number;
  donorName: string;
  email: string;
  phone?: string | null;
  campaign: number | Campaign;
  fundingPool?: (number | null) | CampaignFundingPool;
  qurbaniOrder?: (number | null) | QurbaniOrder;
  qurbaniCheckout?: (number | null) | QurbaniCheckout;
  grossAmount: number;
  netConfirmedAmount: number;
  currency: 'TRY' | 'USD' | 'EUR' | 'GBP';
  status: 'paid' | 'pending_review' | 'failed' | 'cancelled' | 'partially_refunded' | 'refunded';
  paymentId: string;
  receiptNumber: string;
  paymentSession: number | PaymentSession;
  taxReceiptRequested?: boolean | null;
  donationNote?: string | null;
  receiptPath?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-sessions".
 */
export interface PaymentSession {
  id: number;
  donationIntent: number | DonationIntent;
  conversationId: string;
  checkoutToken?: string | null;
  checkoutFormContent?: string | null;
  paymentPageUrl?: string | null;
  providerStatus?: string | null;
  fraudStatus?: number | null;
  paymentId?: string | null;
  lastFourDigits?: string | null;
  cardAssociation?: string | null;
  rawResponse?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-inventory-holds".
 */
export interface QurbaniInventoryHold {
  id: number;
  checkout: number | QurbaniCheckout;
  checkoutLine: number | QurbaniCheckoutLine;
  pool: number | QurbaniPool;
  priceRevision: number | QurbaniPriceRevision;
  quantity: number;
  status: 'active' | 'consumed' | 'released' | 'expired';
  expiresAt: string;
  consumedAt?: string | null;
  releasedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-shares".
 */
export interface QurbaniShare {
  id: number;
  order: number | QurbaniOrder;
  pool: number | QurbaniPool;
  ownerName: string;
  ownerPhone?: string | null;
  effectivePhone: string;
  sequence: number;
  status: 'reserved' | 'confirmed' | 'cancelled' | 'action_required';
  confirmedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-allocations".
 */
export interface QurbaniAllocation {
  id: number;
  checkout: number | QurbaniCheckout;
  checkoutLine: number | QurbaniCheckoutLine;
  order: number | QurbaniOrder;
  pool: number | QurbaniPool;
  hold: number | QurbaniInventoryHold;
  priceRevision: number | QurbaniPriceRevision;
  quantity: number;
  status: 'confirmed' | 'released' | 'action_required';
  providerPaymentId: string;
  idempotencyKey: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-field-packages".
 */
export interface QurbaniFieldPackage {
  id: number;
  season: number | QurbaniSeason;
  country: number | QurbaniCountry;
  region?: (number | null) | QurbaniRegion;
  code: string;
  name: string;
  idempotencyKey: string;
  status: 'draft' | 'assigned' | 'in_progress' | 'completed' | 'cancelled';
  assignedTo?: (number | null) | User;
  dueAt?: string | null;
  startedAt?: string | null;
  completedAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-field-package-items".
 */
export interface QurbaniFieldPackageItem {
  id: number;
  fieldPackage: number | QurbaniFieldPackage;
  pool: number | QurbaniPool;
  ordinal: number;
  status: 'planned' | 'in_progress' | 'completed' | 'failed';
  fieldTask?: (number | null) | FieldTask;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-documents".
 */
export interface QurbaniDocument {
  id: number;
  stockBatch: number | QurbaniStockBatch;
  kind: 'invoice' | 'veterinary' | 'contract' | 'slaughterhouse' | 'ear_tag_list' | 'transport' | 'other';
  title: string;
  storageKey: string;
  fileName: string;
  mimeType: 'application/pdf' | 'image/jpeg' | 'image/png';
  sizeBytes: number;
  isPublic: boolean;
  status: 'active' | 'archived';
  archivedBy?: (number | null) | User;
  archivedAt?: string | null;
  archiveReason?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-videos".
 */
export interface QurbaniVideo {
  id: number;
  pool: number | QurbaniPool;
  fieldTask: number | FieldTask;
  uploadedBy: number | User;
  uploadId: string;
  rawStorageKey: string;
  processedStorageKey?: string | null;
  thumbnailStorageKey?: string | null;
  originalFilename: string;
  mimeType: string;
  sizeBytes: number;
  durationSeconds?: number | null;
  status:
    | 'uploading'
    | 'uploaded'
    | 'processing'
    | 'ready_to_send'
    | 'ready_for_review'
    | 'approved'
    | 'superseded'
    | 'rejected'
    | 'failed';
  version: number;
  replacesVideo?: (number | null) | QurbaniVideo;
  readyAt?: string | null;
  correctionRequired: boolean;
  attemptCount: number;
  lastError?: string | null;
  approvedAt?: string | null;
  approvedBy?: (number | null) | User;
  rawDeleteAfter?: string | null;
  processedDeleteAfter?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-access-links".
 */
export interface QurbaniAccessLink {
  id: number;
  pool: number | QurbaniPool;
  order: number | QurbaniOrder;
  video: number | QurbaniVideo;
  tokenDigest: string;
  recipientPhone: string;
  recipientPhoneHash: string;
  shareIds:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  shares: (number | QurbaniShare)[];
  expiresAt: string;
  revokedAt?: string | null;
  lastAccessedAt?: string | null;
  accessCount: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-messages".
 */
export interface QurbaniMessage {
  id: number;
  pool: number | QurbaniPool;
  accessLink: number | QurbaniAccessLink;
  channel: 'whatsapp' | 'sms';
  recipientPhone: string;
  recipientPhoneHash: string;
  shareSummary:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  body: string;
  idempotencyKey: string;
  status: 'queued' | 'paused' | 'sending' | 'sent' | 'delivered' | 'read' | 'failed' | 'cancelled';
  dispatchBatchId?: string | null;
  scheduledAt?: string | null;
  providerMessageId?: string | null;
  attemptCount: number;
  lastError?: string | null;
  sentAt?: string | null;
  deliveredAt?: string | null;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-jobs".
 */
export interface QurbaniJob {
  id: number;
  type: 'expire_reservations' | 'process_video' | 'purge_storage' | 'send_whatsapp';
  status: 'queued' | 'paused' | 'processing' | 'completed' | 'failed' | 'dead' | 'cancelled';
  order?: (number | null) | QurbaniOrder;
  pool?: (number | null) | QurbaniPool;
  video?: (number | null) | QurbaniVideo;
  message?: (number | null) | QurbaniMessage;
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  idempotencyKey?: string | null;
  runAt: string;
  lockedAt?: string | null;
  lockedBy?: string | null;
  attemptCount: number;
  maxAttempts: number;
  lastError?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "panel-settings".
 */
export interface PanelSetting {
  id: number;
  quickLinks:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-events".
 */
export interface PaymentEvent {
  id: number;
  eventType: string;
  referenceId: string;
  headers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  signatureVerified?: boolean | null;
  processedAt?: string | null;
  paymentSession?: (number | null) | PaymentSession;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-fulfillments".
 */
export interface DonationFulfillment {
  id: number;
  donation: number | Donation;
  status: 'pending' | 'processing' | 'completed' | 'action_required';
  receiptStatus: 'pending' | 'stored' | 'failed' | 'not_requested';
  reportStatus: 'pending' | 'created' | 'failed';
  emailStatus: 'pending' | 'sent' | 'failed' | 'skipped';
  attemptCount: number;
  lastAttemptAt?: string | null;
  lastError?: string | null;
  emailMessageId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refund-requests".
 */
export interface RefundRequest {
  id: number;
  donation: number | Donation;
  type: 'cancel' | 'refund_full' | 'refund_partial';
  reason: string;
  description?: string | null;
  amount?: number | null;
  providerReference?: string | null;
  providerResponse?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('pending' | 'completed' | 'failed') | null;
  requestedBy: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proof-submissions".
 */
export interface ProofSubmission {
  id: number;
  title: string;
  fieldTask: number | FieldTask;
  donation?: (number | null) | Donation;
  campaign?: (number | null) | Campaign;
  summary?: string | null;
  externalApprovalCode?: string | null;
  externalReferenceId?: string | null;
  reviewNotes?: string | null;
  status?: ('draft' | 'submitted' | 'external_pending' | 'review_pending' | 'approved' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proof-assets".
 */
export interface ProofAsset {
  id: number;
  submission: number | ProofSubmission;
  kind: 'document' | 'photo' | 'video';
  storagePath: string;
  fileName: string;
  mimeType: string;
  size?: number | null;
  caption?: string | null;
  isDonorVisible?: boolean | null;
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donor-reports".
 */
export interface DonorReport {
  id: number;
  title: string;
  donation: number | Donation;
  proofSubmissions?: (number | ProofSubmission)[] | null;
  summaryForDonor?: string | null;
  status?: ('draft' | 'approved' | 'sent' | 'stopped') | null;
  approvedBy?: (number | null) | User;
  sentAt?: string | null;
  sentEmailTo?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action: string;
  actorEmail?: string | null;
  targetCollection?: string | null;
  targetId?: string | null;
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'campaigns';
        value: number | Campaign;
      } | null)
    | ({
        relationTo: 'campaign-funding-pools';
        value: number | CampaignFundingPool;
      } | null)
    | ({
        relationTo: 'news-categories';
        value: number | NewsCategory;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'qurbani-seasons';
        value: number | QurbaniSeason;
      } | null)
    | ({
        relationTo: 'qurbani-countries';
        value: number | QurbaniCountry;
      } | null)
    | ({
        relationTo: 'qurbani-regions';
        value: number | QurbaniRegion;
      } | null)
    | ({
        relationTo: 'qurbani-products';
        value: number | QurbaniProduct;
      } | null)
    | ({
        relationTo: 'qurbani-stock-batches';
        value: number | QurbaniStockBatch;
      } | null)
    | ({
        relationTo: 'qurbani-stock-batch-lines';
        value: number | QurbaniStockBatchLine;
      } | null)
    | ({
        relationTo: 'qurbani-price-revisions';
        value: number | QurbaniPriceRevision;
      } | null)
    | ({
        relationTo: 'qurbani-pools';
        value: number | QurbaniPool;
      } | null)
    | ({
        relationTo: 'qurbani-checkouts';
        value: number | QurbaniCheckout;
      } | null)
    | ({
        relationTo: 'qurbani-checkout-lines';
        value: number | QurbaniCheckoutLine;
      } | null)
    | ({
        relationTo: 'qurbani-inventory-holds';
        value: number | QurbaniInventoryHold;
      } | null)
    | ({
        relationTo: 'qurbani-orders';
        value: number | QurbaniOrder;
      } | null)
    | ({
        relationTo: 'qurbani-shares';
        value: number | QurbaniShare;
      } | null)
    | ({
        relationTo: 'qurbani-allocations';
        value: number | QurbaniAllocation;
      } | null)
    | ({
        relationTo: 'qurbani-field-packages';
        value: number | QurbaniFieldPackage;
      } | null)
    | ({
        relationTo: 'qurbani-field-package-items';
        value: number | QurbaniFieldPackageItem;
      } | null)
    | ({
        relationTo: 'qurbani-documents';
        value: number | QurbaniDocument;
      } | null)
    | ({
        relationTo: 'qurbani-videos';
        value: number | QurbaniVideo;
      } | null)
    | ({
        relationTo: 'qurbani-access-links';
        value: number | QurbaniAccessLink;
      } | null)
    | ({
        relationTo: 'qurbani-messages';
        value: number | QurbaniMessage;
      } | null)
    | ({
        relationTo: 'qurbani-jobs';
        value: number | QurbaniJob;
      } | null)
    | ({
        relationTo: 'donation-intents';
        value: number | DonationIntent;
      } | null)
    | ({
        relationTo: 'payment-sessions';
        value: number | PaymentSession;
      } | null)
    | ({
        relationTo: 'panel-settings';
        value: number | PanelSetting;
      } | null)
    | ({
        relationTo: 'payment-events';
        value: number | PaymentEvent;
      } | null)
    | ({
        relationTo: 'donations';
        value: number | Donation;
      } | null)
    | ({
        relationTo: 'donation-fulfillments';
        value: number | DonationFulfillment;
      } | null)
    | ({
        relationTo: 'refund-requests';
        value: number | RefundRequest;
      } | null)
    | ({
        relationTo: 'field-tasks';
        value: number | FieldTask;
      } | null)
    | ({
        relationTo: 'proof-submissions';
        value: number | ProofSubmission;
      } | null)
    | ({
        relationTo: 'proof-assets';
        value: number | ProofAsset;
      } | null)
    | ({
        relationTo: 'donor-reports';
        value: number | DonorReport;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  isActive?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  icon?: T;
  color?: T;
  slug?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns_select".
 */
export interface CampaignsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  targetAmount?: T;
  collectedAmount?: T;
  coverImagePath?: T;
  coverImageAlt?: T;
  code?: T;
  image?: T;
  category?: T;
  currency?: T;
  reportingMode?: T;
  isDonationOpen?: T;
  slug?: T;
  donorCount?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaign-funding-pools_select".
 */
export interface CampaignFundingPoolsSelect<T extends boolean = true> {
  campaign?: T;
  internalLabel?: T;
  currency?: T;
  targetAmount?: T;
  collectedAmount?: T;
  donorCount?: T;
  reportingMode?: T;
  isDonationOpen?: T;
  availableLocales?: T;
  title?: T;
  description?: T;
  category?: T;
  coverImageAlt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-categories_select".
 */
export interface NewsCategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  slug?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  image?: T;
  category?: T;
  newsCategory?: T;
  availableLocales?: T;
  excerpt?: T;
  contentBlocks?: T;
  tags?: T;
  searchText?: T;
  readTimeMinutes?: T;
  coverImagePath?: T;
  coverImageAlt?: T;
  relatedCampaigns?: T;
  status?: T;
  featured?: T;
  sortOrder?: T;
  viewCount?: T;
  publishedAt?: T;
  slug?: T;
  author?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  slug?: T;
  published?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-seasons_select".
 */
export interface QurbaniSeasonsSelect<T extends boolean = true> {
  year?: T;
  status?: T;
  salesStartAt?: T;
  salesEndAt?: T;
  eidAt?: T;
  codeCounter?: T;
  availableLocales?: T;
  heroTitle?: T;
  heroDescription?: T;
  pageContent?: T;
  processSteps?: T;
  heroImage?: T;
  bankName?: T;
  accountHolder?: T;
  iban?: T;
  bankBranch?: T;
  eftDescription?: T;
  proxyTextVersion?: T;
  proxyText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-countries_select".
 */
export interface QurbaniCountriesSelect<T extends boolean = true> {
  isoCode?: T;
  slug?: T;
  name?: T;
  description?: T;
  image?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-regions_select".
 */
export interface QurbaniRegionsSelect<T extends boolean = true> {
  season?: T;
  country?: T;
  slug?: T;
  name?: T;
  description?: T;
  publicContent?: T;
  image?: T;
  salesStartAt?: T;
  salesEndAt?: T;
  fieldPreparationAt?: T;
  countdownAt?: T;
  codeCounter?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-products_select".
 */
export interface QurbaniProductsSelect<T extends boolean = true> {
  season?: T;
  country?: T;
  regionRef?: T;
  campaign?: T;
  fundingPool?: T;
  title?: T;
  description?: T;
  region?: T;
  image?: T;
  kind?: T;
  price?: T;
  currency?: T;
  capacity?: T;
  salesStartAt?: T;
  salesEndAt?: T;
  sortOrder?: T;
  isActive?: T;
  currentPriceRevision?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-stock-batches_select".
 */
export interface QurbaniStockBatchesSelect<T extends boolean = true> {
  season?: T;
  country?: T;
  region?: T;
  code?: T;
  name?: T;
  nature?: T;
  status?: T;
  idempotencyKey?: T;
  animalCount?: T;
  totalCapacity?: T;
  availableCapacity?: T;
  salesStartAt?: T;
  salesEndAt?: T;
  createdBy?: T;
  notes?: T;
  isLegacy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-stock-batch-lines_select".
 */
export interface QurbaniStockBatchLinesSelect<T extends boolean = true> {
  batch?: T;
  product?: T;
  kind?: T;
  animalCount?: T;
  capacity?: T;
  totalQuantity?: T;
  priceRevision?: T;
  status?: T;
  salesStartAt?: T;
  salesEndAt?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-price-revisions_select".
 */
export interface QurbaniPriceRevisionsSelect<T extends boolean = true> {
  product?: T;
  batchLine?: T;
  revision?: T;
  unitPrice?: T;
  currency?: T;
  status?: T;
  effectiveFrom?: T;
  effectiveTo?: T;
  createdBy?: T;
  reason?: T;
  isLegacy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-pools_select".
 */
export interface QurbaniPoolsSelect<T extends boolean = true> {
  season?: T;
  product?: T;
  country?: T;
  stockBatchLine?: T;
  priceRevision?: T;
  ordinal?: T;
  code?: T;
  capacity?: T;
  reservedCount?: T;
  confirmedCount?: T;
  status?: T;
  fieldTask?: T;
  fullAt?: T;
  lockedAt?: T;
  actionRequired?: T;
  operationNotes?: T;
  isLegacy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-checkouts_select".
 */
export interface QurbaniCheckoutsSelect<T extends boolean = true> {
  publicId?: T;
  buyerMask?: T;
  buyerHash?: T;
  encryptedPayload?: T;
  encryptionIv?: T;
  encryptionTag?: T;
  encryptionKeyVersion?: T;
  campaign?: T;
  fundingPool?: T;
  totalAmount?: T;
  currency?: T;
  status?: T;
  source?: T;
  providerConversationId?: T;
  providerPaymentId?: T;
  donationIntent?: T;
  donation?: T;
  expiresAt?: T;
  finalizedAt?: T;
  ipAddress?: T;
  failureCode?: T;
  piiPurgeAt?: T;
  piiPurgedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-checkout-lines_select".
 */
export interface QurbaniCheckoutLinesSelect<T extends boolean = true> {
  checkout?: T;
  product?: T;
  stockBatchLine?: T;
  priceRevision?: T;
  quantity?: T;
  participantCount?: T;
  encryptedItemIndex?: T;
  unitPrice?: T;
  totalAmount?: T;
  currency?: T;
  status?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-inventory-holds_select".
 */
export interface QurbaniInventoryHoldsSelect<T extends boolean = true> {
  checkout?: T;
  checkoutLine?: T;
  pool?: T;
  priceRevision?: T;
  quantity?: T;
  status?: T;
  expiresAt?: T;
  consumedAt?: T;
  releasedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-orders_select".
 */
export interface QurbaniOrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  season?: T;
  product?: T;
  pool?: T;
  checkout?: T;
  checkoutLine?: T;
  priceRevision?: T;
  donationIntent?: T;
  donation?: T;
  buyerName?: T;
  buyerEmail?: T;
  buyerPhone?: T;
  countryCode?: T;
  identityType?: T;
  identityNumber?: T;
  addressSnapshot?: T;
  productSnapshot?: T;
  unitPrice?: T;
  shareCount?: T;
  totalAmount?: T;
  currency?: T;
  paymentMethod?: T;
  reservationKind?: T;
  status?: T;
  reservedUntil?: T;
  providerPaymentId?: T;
  providerReference?: T;
  eftProofBucket?: T;
  eftProofPath?: T;
  eftProofMimeType?: T;
  eftReviewedAt?: T;
  eftReviewedBy?: T;
  proxyTextVersion?: T;
  proxyAcceptedAt?: T;
  proxyAcceptedIp?: T;
  phoneProxyConfirmedAt?: T;
  phoneProxyConfirmedBy?: T;
  kvkkAcceptedAt?: T;
  termsAcceptedAt?: T;
  thirdPartyContactConsentAt?: T;
  paidAt?: T;
  failureReason?: T;
  isLegacy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-shares_select".
 */
export interface QurbaniSharesSelect<T extends boolean = true> {
  order?: T;
  pool?: T;
  ownerName?: T;
  ownerPhone?: T;
  effectivePhone?: T;
  sequence?: T;
  status?: T;
  confirmedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-allocations_select".
 */
export interface QurbaniAllocationsSelect<T extends boolean = true> {
  checkout?: T;
  checkoutLine?: T;
  order?: T;
  pool?: T;
  hold?: T;
  priceRevision?: T;
  quantity?: T;
  status?: T;
  providerPaymentId?: T;
  idempotencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-field-packages_select".
 */
export interface QurbaniFieldPackagesSelect<T extends boolean = true> {
  season?: T;
  country?: T;
  region?: T;
  code?: T;
  name?: T;
  idempotencyKey?: T;
  status?: T;
  assignedTo?: T;
  dueAt?: T;
  startedAt?: T;
  completedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-field-package-items_select".
 */
export interface QurbaniFieldPackageItemsSelect<T extends boolean = true> {
  fieldPackage?: T;
  pool?: T;
  ordinal?: T;
  status?: T;
  fieldTask?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-documents_select".
 */
export interface QurbaniDocumentsSelect<T extends boolean = true> {
  stockBatch?: T;
  kind?: T;
  title?: T;
  storageKey?: T;
  fileName?: T;
  mimeType?: T;
  sizeBytes?: T;
  isPublic?: T;
  status?: T;
  archivedBy?: T;
  archivedAt?: T;
  archiveReason?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-videos_select".
 */
export interface QurbaniVideosSelect<T extends boolean = true> {
  pool?: T;
  fieldTask?: T;
  uploadedBy?: T;
  uploadId?: T;
  rawStorageKey?: T;
  processedStorageKey?: T;
  thumbnailStorageKey?: T;
  originalFilename?: T;
  mimeType?: T;
  sizeBytes?: T;
  durationSeconds?: T;
  status?: T;
  version?: T;
  replacesVideo?: T;
  readyAt?: T;
  correctionRequired?: T;
  attemptCount?: T;
  lastError?: T;
  approvedAt?: T;
  approvedBy?: T;
  rawDeleteAfter?: T;
  processedDeleteAfter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-access-links_select".
 */
export interface QurbaniAccessLinksSelect<T extends boolean = true> {
  pool?: T;
  order?: T;
  video?: T;
  tokenDigest?: T;
  recipientPhone?: T;
  recipientPhoneHash?: T;
  shareIds?: T;
  shares?: T;
  expiresAt?: T;
  revokedAt?: T;
  lastAccessedAt?: T;
  accessCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-messages_select".
 */
export interface QurbaniMessagesSelect<T extends boolean = true> {
  pool?: T;
  accessLink?: T;
  channel?: T;
  recipientPhone?: T;
  recipientPhoneHash?: T;
  shareSummary?: T;
  body?: T;
  idempotencyKey?: T;
  status?: T;
  dispatchBatchId?: T;
  scheduledAt?: T;
  providerMessageId?: T;
  attemptCount?: T;
  lastError?: T;
  sentAt?: T;
  deliveredAt?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qurbani-jobs_select".
 */
export interface QurbaniJobsSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  order?: T;
  pool?: T;
  video?: T;
  message?: T;
  payload?: T;
  idempotencyKey?: T;
  runAt?: T;
  lockedAt?: T;
  lockedBy?: T;
  attemptCount?: T;
  maxAttempts?: T;
  lastError?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-intents_select".
 */
export interface DonationIntentsSelect<T extends boolean = true> {
  conversationId?: T;
  donorName?: T;
  email?: T;
  phone?: T;
  campaign?: T;
  fundingPool?: T;
  qurbaniOrder?: T;
  qurbaniCheckout?: T;
  amount?: T;
  currency?: T;
  status?: T;
  note?: T;
  taxReceiptRequested?: T;
  kvkkAcceptedAt?: T;
  termsAcceptedAt?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-sessions_select".
 */
export interface PaymentSessionsSelect<T extends boolean = true> {
  donationIntent?: T;
  conversationId?: T;
  checkoutToken?: T;
  checkoutFormContent?: T;
  paymentPageUrl?: T;
  providerStatus?: T;
  fraudStatus?: T;
  paymentId?: T;
  lastFourDigits?: T;
  cardAssociation?: T;
  rawResponse?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "panel-settings_select".
 */
export interface PanelSettingsSelect<T extends boolean = true> {
  quickLinks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-events_select".
 */
export interface PaymentEventsSelect<T extends boolean = true> {
  eventType?: T;
  referenceId?: T;
  headers?: T;
  payload?: T;
  signatureVerified?: T;
  processedAt?: T;
  paymentSession?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations_select".
 */
export interface DonationsSelect<T extends boolean = true> {
  donorName?: T;
  email?: T;
  phone?: T;
  campaign?: T;
  fundingPool?: T;
  qurbaniOrder?: T;
  qurbaniCheckout?: T;
  grossAmount?: T;
  netConfirmedAmount?: T;
  currency?: T;
  status?: T;
  paymentId?: T;
  receiptNumber?: T;
  paymentSession?: T;
  taxReceiptRequested?: T;
  donationNote?: T;
  receiptPath?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-fulfillments_select".
 */
export interface DonationFulfillmentsSelect<T extends boolean = true> {
  donation?: T;
  status?: T;
  receiptStatus?: T;
  reportStatus?: T;
  emailStatus?: T;
  attemptCount?: T;
  lastAttemptAt?: T;
  lastError?: T;
  emailMessageId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refund-requests_select".
 */
export interface RefundRequestsSelect<T extends boolean = true> {
  donation?: T;
  type?: T;
  reason?: T;
  description?: T;
  amount?: T;
  providerReference?: T;
  providerResponse?: T;
  status?: T;
  requestedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "field-tasks_select".
 */
export interface FieldTasksSelect<T extends boolean = true> {
  campaign?: T;
  qurbaniPool?: T;
  title?: T;
  location?: T;
  assignedTo?: T;
  dueAt?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proof-submissions_select".
 */
export interface ProofSubmissionsSelect<T extends boolean = true> {
  title?: T;
  fieldTask?: T;
  donation?: T;
  campaign?: T;
  summary?: T;
  externalApprovalCode?: T;
  externalReferenceId?: T;
  reviewNotes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proof-assets_select".
 */
export interface ProofAssetsSelect<T extends boolean = true> {
  submission?: T;
  kind?: T;
  storagePath?: T;
  fileName?: T;
  mimeType?: T;
  size?: T;
  caption?: T;
  isDonorVisible?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donor-reports_select".
 */
export interface DonorReportsSelect<T extends boolean = true> {
  title?: T;
  donation?: T;
  proofSubmissions?: T;
  summaryForDonor?: T;
  status?: T;
  approvedBy?: T;
  sentAt?: T;
  sentEmailTo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  actorEmail?: T;
  targetCollection?: T;
  targetId?: T;
  details?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
