/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    'contact-messages': ContactMessage;
    'child-donation-settings': ChildDonationSetting;
    campaigns: Campaign;
    'news-categories': NewsCategory;
    news: News;
    pages: Page;
    'panel-settings': PanelSetting;
    'donation-intents': DonationIntent;
    'donation-participants': DonationParticipant;
    'payment-sessions': PaymentSession;
    'payment-events': PaymentEvent;
    donations: Donation;
    'operation-groups': OperationGroup;
    'operation-group-members': OperationGroupMember;
    'operation-videos': OperationVideo;
    'delivery-messages': DeliveryMessage;
    'donation-fulfillments': DonationFulfillment;
    'refund-requests': RefundRequest;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'child-donation-settings': ChildDonationSettingsSelect<false> | ChildDonationSettingsSelect<true>;
    campaigns: CampaignsSelect<false> | CampaignsSelect<true>;
    'news-categories': NewsCategoriesSelect<false> | NewsCategoriesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'panel-settings': PanelSettingsSelect<false> | PanelSettingsSelect<true>;
    'donation-intents': DonationIntentsSelect<false> | DonationIntentsSelect<true>;
    'donation-participants': DonationParticipantsSelect<false> | DonationParticipantsSelect<true>;
    'payment-sessions': PaymentSessionsSelect<false> | PaymentSessionsSelect<true>;
    'payment-events': PaymentEventsSelect<false> | PaymentEventsSelect<true>;
    donations: DonationsSelect<false> | DonationsSelect<true>;
    'operation-groups': OperationGroupsSelect<false> | OperationGroupsSelect<true>;
    'operation-group-members': OperationGroupMembersSelect<false> | OperationGroupMembersSelect<true>;
    'operation-videos': OperationVideosSelect<false> | OperationVideosSelect<true>;
    'delivery-messages': DeliveryMessagesSelect<false> | DeliveryMessagesSelect<true>;
    'donation-fulfillments': DonationFulfillmentsSelect<false> | DonationFulfillmentsSelect<true>;
    'refund-requests': RefundRequestsSelect<false> | RefundRequestsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('tr' | 'en' | 'ar') | ('tr' | 'en' | 'ar')[];
  globals: {};
  globalsSelect: {};
  locale: 'tr' | 'en' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  phone?: string | null;
  role: 'admin' | 'field_operator';
  isActive?: boolean | null;
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Material Symbols icon name (e.g. "favorite", "volunteer_activism")
   */
  icon?: string | null;
  /**
   * Hex color code (e.g. #10B981)
   */
  color?: string | null;
  slug: string;
  sortOrder?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  type: 'contact' | 'student';
  name: string;
  email: string;
  phone?: string | null;
  subject?: string | null;
  program?: string | null;
  message?: string | null;
  privacyConsent: boolean;
  status: 'unread' | 'read' | 'archived';
  readAt?: string | null;
  readBy?: (number | null) | User;
  emailNotificationStatus?: ('sent' | 'failed' | 'skipped') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "child-donation-settings".
 */
export interface ChildDonationSetting {
  id: number;
  campaign: number | Campaign;
  usdCampaign: number | Campaign;
  eurCampaign: number | Campaign;
  foodPrice: number;
  stationeryPrice: number;
  toyPrice: number;
  clothingPrice: number;
  foodUsdPrice: number;
  stationeryUsdPrice: number;
  toyUsdPrice: number;
  clothingUsdPrice: number;
  foodEurPrice: number;
  stationeryEurPrice: number;
  toyEurPrice: number;
  clothingEurPrice: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns".
 */
export interface Campaign {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  targetAmount?: number | null;
  pricingModel: 'free' | 'fixed';
  unitPrice?: number | null;
  unitLabel?: string | null;
  totalStock?: number | null;
  reservedUnits: number;
  confirmedUnits: number;
  videoDelivery: 'none' | 'video';
  /**
   * Videolu kampanyalarda kategori adından türetilmez; açıkça seçilmelidir.
   */
  operationType?: ('standard_video' | 'slaughter_video') | null;
  groupCapacity?: number | null;
  participantRequired: boolean;
  publishStartAt?: string | null;
  publishEndAt?: string | null;
  messageTemplate?: string | null;
  /**
   * Kesim öncesi okunacak metin. Değişiklikler yeni videoları etkiler; eski videolar snapshot taşır.
   */
  slaughterScript?: string | null;
  slaughterScriptVersion?: number | null;
  /**
   * Hissedar adı okuma ve üçüncü kişi onay metinleri canlı öncesi hukuk/KVKK kontrolü gerektirir.
   */
  consentLegalReviewRequired: boolean;
  status: 'draft' | 'active' | 'paused' | 'closed' | 'archived';
  pauseReason?: string | null;
  pausedAt?: string | null;
  pausedBy?: (number | null) | User;
  closeReason?: string | null;
  closedAt?: string | null;
  closedBy?: (number | null) | User;
  collectedAmount?: number | null;
  coverImagePath?: string | null;
  coverImageAlt?: string | null;
  code: string;
  image?: (number | null) | Media;
  category?: (number | null) | Category;
  currency?: ('TRY' | 'USD' | 'EUR' | 'GBP') | null;
  reportingMode?: ('pool' | 'donation_based') | null;
  isDonationOpen?: boolean | null;
  slug: string;
  donorCount?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-categories".
 */
export interface NewsCategory {
  id: number;
  name: string;
  description?: string | null;
  slug: string;
  sortOrder?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  category?: ('haber' | 'etkinlik' | 'duyuru' | 'proje') | null;
  newsCategory?: (number | null) | NewsCategory;
  availableLocales:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  excerpt?: string | null;
  contentBlocks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  searchText?: string | null;
  readTimeMinutes?: number | null;
  coverImagePath?: string | null;
  coverImageAlt?: string | null;
  relatedCampaigns?: (number | Campaign)[] | null;
  status: 'draft' | 'published' | 'archived';
  featured?: boolean | null;
  sortOrder?: number | null;
  viewCount?: number | null;
  publishedAt?: string | null;
  slug: string;
  author?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  slug: string;
  published?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "panel-settings".
 */
export interface PanelSetting {
  id: number;
  quickLinks:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-intents".
 */
export interface DonationIntent {
  id: number;
  conversationId: string;
  donorName: string;
  email: string;
  phone?: string | null;
  address?: string | null;
  city?: string | null;
  countryCode?: string | null;
  campaign: number | Campaign;
  quantity: number;
  unitPriceSnapshot?: number | null;
  amount: number;
  currency: 'TRY' | 'USD' | 'EUR' | 'GBP';
  status?:
    | (
        | 'draft'
        | 'reserved'
        | 'payment_initialized'
        | 'awaiting_bank_transfer'
        | 'bank_transfer_submitted'
        | 'callback_received'
        | 'completed'
        | 'failed'
        | 'expired'
        | 'cancelled'
      )
    | null;
  paymentMethod: 'card' | 'bank_transfer';
  reservationExpiresAt?: string | null;
  note?: string | null;
  taxReceiptRequested?: boolean | null;
  kvkkAcceptedAt?: string | null;
  termsAcceptedAt?: string | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-participants".
 */
export interface DonationParticipant {
  id: number;
  donationIntent: number | DonationIntent;
  donation?: (number | null) | Donation;
  orderIndex: number;
  name: string;
  phone?: string | null;
  effectivePhone: string;
  isPayer: boolean;
  contactConsent: boolean;
  proxyConsent: boolean;
  /**
   * Hissedar adının aynı gruba gönderilen kesim videosunda duyulmasına ilişkin ayrı açık onay.
   */
  nameReadingConsent: boolean;
  nameReadingConsentTextVersion?: string | null;
  nameReadingConsentTextSnapshot?: string | null;
  nameReadingConsentAcceptedAt?: string | null;
  nameReadingConsentIp?: string | null;
  /**
   * Katılımcının üçüncü kişi bilgilerini paylaşmaya yetkili olduğuna ilişkin ayrı onay.
   */
  thirdPartyDataAuthorityConsent: boolean;
  thirdPartyDataAuthorityTextVersion?: string | null;
  thirdPartyDataAuthorityTextSnapshot?: string | null;
  thirdPartyDataAuthorityAcceptedAt?: string | null;
  thirdPartyDataAuthorityIp?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations".
 */
export interface Donation {
  id: number;
  donorName: string;
  email: string;
  phone?: string | null;
  campaign: number | Campaign;
  donationIntent: number | DonationIntent;
  quantity: number;
  unitPriceSnapshot?: number | null;
  grossAmount: number;
  netConfirmedAmount: number;
  currency: 'TRY' | 'USD' | 'EUR' | 'GBP';
  status: 'paid' | 'pending_review' | 'failed' | 'cancelled' | 'partially_refunded' | 'refunded';
  paymentId: string;
  receiptNumber: string;
  paymentSession: number | PaymentSession;
  paymentMethod: 'card' | 'bank_transfer';
  confirmedAt?: string | null;
  taxReceiptRequested?: boolean | null;
  donationNote?: string | null;
  receiptPath?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-sessions".
 */
export interface PaymentSession {
  id: number;
  donationIntent: number | DonationIntent;
  conversationId: string;
  paymentMethod: 'card' | 'bank_transfer';
  reservationExpiresAt?: string | null;
  checkoutToken?: string | null;
  checkoutFormContent?: string | null;
  paymentPageUrl?: string | null;
  providerStatus?: string | null;
  fraudStatus?: number | null;
  paymentId?: string | null;
  lastFourDigits?: string | null;
  cardAssociation?: string | null;
  eftProofBucket?: string | null;
  eftProofPath?: string | null;
  eftReviewStatus?: ('pending' | 'approved' | 'rejected') | null;
  eftReviewedAt?: string | null;
  eftReviewedBy?: (number | null) | User;
  rawResponse?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-events".
 */
export interface PaymentEvent {
  id: number;
  eventType: string;
  referenceId: string;
  headers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  signatureVerified?: boolean | null;
  processedAt?: string | null;
  paymentSession?: (number | null) | PaymentSession;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operation-groups".
 */
export interface OperationGroup {
  id: number;
  campaign: number | Campaign;
  code: string;
  operationType?: ('standard_video' | 'slaughter_video') | null;
  year: number;
  ordinal: number;
  capacity?: number | null;
  reservedCount: number;
  confirmedCount: number;
  status:
    | 'collecting'
    | 'full'
    | 'ready_for_slaughter'
    | 'scheduled'
    | 'slaughtered'
    | 'video_pending'
    | 'video_ready'
    | 'delivery_started'
    | 'completed'
    | 'open'
    | 'notified'
    | 'closed'
    | 'action_required';
  capacityOverrideOriginal?: number | null;
  capacityOverrideReason?: string | null;
  capacityOverrideCoveredByAssociation?: boolean | null;
  capacityOverriddenAt?: string | null;
  capacityOverriddenBy?: (number | null) | User;
  slaughterScheduledAt?: string | null;
  slaughterOrder?: number | null;
  slaughterPlace?: string | null;
  assignedOperator?: (number | null) | User;
  fieldNotes?: string | null;
  slaughteredAt?: string | null;
  slaughteredBy?: (number | null) | User;
  slaughterRevertedAt?: string | null;
  slaughterRevertedBy?: (number | null) | User;
  slaughterRevertReason?: string | null;
  slaughterScriptSnapshot?: string | null;
  groupCodeConfirmationFailures: number;
  groupCodeLockedUntil?: string | null;
  activeVideo?: (number | null) | OperationVideo;
  publicLinkTokenHash?: string | null;
  accessCodeHash?: string | null;
  accessCodeCiphertext?: string | null;
  accessCodeRotatedAt?: string | null;
  accessCodeRotatedBy?: (number | null) | User;
  accessCodeRotationCount: number;
  expiresAt?: string | null;
  extensionUsed: boolean;
  extendedAt?: string | null;
  extendedBy?: (number | null) | User;
  testMessageVideo?: (number | null) | OperationVideo;
  testMessageFingerprint?: string | null;
  testMessagePassedAt?: string | null;
  testMessagePassedBy?: (number | null) | User;
  testMessageInvalidatedAt?: string | null;
  messageTemplate: string;
  dispatchState: 'idle' | 'countdown' | 'queued' | 'sending' | 'paused' | 'completed' | 'cancelled' | 'failed';
  dispatchLockedAt?: string | null;
  dispatchLockedBy?: string | null;
  dispatchPauseReason?: string | null;
  providerHealthySince?: string | null;
  providerHealthCheckCount: number;
  consecutiveSystemFailures: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operation-videos".
 */
export interface OperationVideo {
  id: number;
  group: number | OperationGroup;
  uploadedBy: number | User;
  uploadId: string;
  rawStorageKey: string;
  processedStorageKey?: string | null;
  thumbnailStorageKey?: string | null;
  originalFilename: string;
  mimeType: string;
  sizeBytes: number;
  durationSeconds?: number | null;
  status:
    | 'uploading'
    | 'uploaded'
    | 'processing'
    | 'review_pending'
    | 'ready'
    | 'superseded'
    | 'rejected'
    | 'failed'
    | 'processing_failed'
    | 'quarantined'
    | 'expired'
    | 'deleted';
  version: number;
  replacesVideo?: (number | null) | OperationVideo;
  versionKind: 'initial' | 'replacement' | 'correction';
  isActive: boolean;
  uploadTokenJti?: string | null;
  uploadNonceHash?: string | null;
  uploadTokenExpiresAt?: string | null;
  uploadTokenConsumedAt?: string | null;
  uploadMaxBytes: number;
  detectedMimeType?: string | null;
  containerFormat?: string | null;
  videoCodec?: string | null;
  audioCodec?: string | null;
  width?: number | null;
  height?: number | null;
  rawSha256?: string | null;
  processedSha256?: string | null;
  technicalMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  processingSettingsSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  watermarkSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  closingCardSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  slaughterScriptSnapshot?: string | null;
  /**
   * Saha görevlisinin içerik kontrol beyanlarıdır; otomatik içerik doğrulaması değildir.
   */
  fieldChecklist:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  fieldCheckedAt?: string | null;
  fieldCheckedBy?: (number | null) | User;
  /**
   * İşlenmiş video için insan tarafından tamamlanan son kontrol listesi.
   */
  reviewChecklist:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reviewedAt?: string | null;
  reviewedBy?: (number | null) | User;
  contentReviewStatus: 'pending' | 'approved' | 'rejected';
  readyAt?: string | null;
  attemptCount: number;
  lastError?: string | null;
  lastErrorCode?: string | null;
  ffmpegLog?: string | null;
  processingStartedAt?: string | null;
  processingFailedAt?: string | null;
  retryAfter?: string | null;
  quarantineUntil?: string | null;
  rawDeleteAfter: string;
  processedDeleteAfter: string;
  expiresAt?: string | null;
  expiredAt?: string | null;
  physicalDeletedAt?: string | null;
  extensionUsed: boolean;
  extendedAt?: string | null;
  extendedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operation-group-members".
 */
export interface OperationGroupMember {
  id: number;
  group: number | OperationGroup;
  donationIntent: number | DonationIntent;
  donation?: (number | null) | Donation;
  participant?: (number | null) | DonationParticipant;
  memberKey: string;
  unitIndex: number;
  status: 'reserved' | 'confirmed' | 'released' | 'refunded' | 'action_required';
  reservationExpiresAt: string;
  confirmedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-messages".
 */
export interface DeliveryMessage {
  id: number;
  group: number | OperationGroup;
  video: number | OperationVideo;
  donation?: (number | null) | Donation;
  participant?: (number | null) | DonationParticipant;
  member?: (number | null) | OperationGroupMember;
  messageType: 'normal' | 'correction' | 'code_renewal' | 'test';
  recipientRole?: ('payer' | 'participant' | 'test') | null;
  recipientPhone?: string | null;
  normalizedPhone?: string | null;
  recipientPhoneHash: string;
  body?: string | null;
  bodySnapshot?: string | null;
  messageSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  systemPayloadSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  idempotencyKey: string;
  status:
    | 'draft'
    | 'countdown'
    | 'queued'
    | 'paused'
    | 'sending'
    | 'sent'
    | 'delivered'
    | 'read'
    | 'failed'
    | 'cancelled'
    | 'manual_sent';
  dispatchBatchId?: string | null;
  scheduledAt?: string | null;
  lockedAt?: string | null;
  lockedBy?: string | null;
  providerMessageId?: string | null;
  providerStatus?: string | null;
  providerPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  attemptCount: number;
  lastError?: string | null;
  lastErrorCode?: string | null;
  retryClass: 'none' | 'transient' | 'permanent' | 'ambiguous';
  nextRetryAt?: string | null;
  lastAttemptAt?: string | null;
  providerLookupAt?: string | null;
  accessTokenDigest: string;
  expiresAt: string;
  sentAt?: string | null;
  deliveredAt?: string | null;
  readAt?: string | null;
  failedAt?: string | null;
  manualSentAt?: string | null;
  manualSentBy?: (number | null) | User;
  manualSentReason?: string | null;
  isTest: boolean;
  testNumberKey?: string | null;
  testFingerprint?: string | null;
  redactedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-fulfillments".
 */
export interface DonationFulfillment {
  id: number;
  donation: number | Donation;
  status: 'pending' | 'processing' | 'completed' | 'action_required';
  receiptStatus: 'pending' | 'stored' | 'failed' | 'not_requested';
  reportStatus: 'pending' | 'created' | 'failed';
  emailStatus: 'pending' | 'sent' | 'failed' | 'skipped';
  attemptCount: number;
  lastAttemptAt?: string | null;
  lastError?: string | null;
  emailMessageId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refund-requests".
 */
export interface RefundRequest {
  id: number;
  donation: number | Donation;
  type: 'cancel' | 'refund_full' | 'refund_partial';
  reason: 'technical_error' | 'wrong_transaction' | 'legal_obligation';
  description: string;
  evidenceBucket: string;
  evidencePath: string;
  evidenceMimeType: string;
  manualReviewRequired?: boolean | null;
  amount?: number | null;
  providerReference?: string | null;
  providerResponse?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('pending' | 'completed' | 'failed') | null;
  requestedBy: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action: string;
  actorEmail?: string | null;
  targetCollection?: string | null;
  targetId?: string | null;
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'child-donation-settings';
        value: number | ChildDonationSetting;
      } | null)
    | ({
        relationTo: 'campaigns';
        value: number | Campaign;
      } | null)
    | ({
        relationTo: 'news-categories';
        value: number | NewsCategory;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'panel-settings';
        value: number | PanelSetting;
      } | null)
    | ({
        relationTo: 'donation-intents';
        value: number | DonationIntent;
      } | null)
    | ({
        relationTo: 'donation-participants';
        value: number | DonationParticipant;
      } | null)
    | ({
        relationTo: 'payment-sessions';
        value: number | PaymentSession;
      } | null)
    | ({
        relationTo: 'payment-events';
        value: number | PaymentEvent;
      } | null)
    | ({
        relationTo: 'donations';
        value: number | Donation;
      } | null)
    | ({
        relationTo: 'operation-groups';
        value: number | OperationGroup;
      } | null)
    | ({
        relationTo: 'operation-group-members';
        value: number | OperationGroupMember;
      } | null)
    | ({
        relationTo: 'operation-videos';
        value: number | OperationVideo;
      } | null)
    | ({
        relationTo: 'delivery-messages';
        value: number | DeliveryMessage;
      } | null)
    | ({
        relationTo: 'donation-fulfillments';
        value: number | DonationFulfillment;
      } | null)
    | ({
        relationTo: 'refund-requests';
        value: number | RefundRequest;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  role?: T;
  isActive?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  icon?: T;
  color?: T;
  slug?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  program?: T;
  message?: T;
  privacyConsent?: T;
  status?: T;
  readAt?: T;
  readBy?: T;
  emailNotificationStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "child-donation-settings_select".
 */
export interface ChildDonationSettingsSelect<T extends boolean = true> {
  campaign?: T;
  usdCampaign?: T;
  eurCampaign?: T;
  foodPrice?: T;
  stationeryPrice?: T;
  toyPrice?: T;
  clothingPrice?: T;
  foodUsdPrice?: T;
  stationeryUsdPrice?: T;
  toyUsdPrice?: T;
  clothingUsdPrice?: T;
  foodEurPrice?: T;
  stationeryEurPrice?: T;
  toyEurPrice?: T;
  clothingEurPrice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns_select".
 */
export interface CampaignsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  targetAmount?: T;
  pricingModel?: T;
  unitPrice?: T;
  unitLabel?: T;
  totalStock?: T;
  reservedUnits?: T;
  confirmedUnits?: T;
  videoDelivery?: T;
  operationType?: T;
  groupCapacity?: T;
  participantRequired?: T;
  publishStartAt?: T;
  publishEndAt?: T;
  messageTemplate?: T;
  slaughterScript?: T;
  slaughterScriptVersion?: T;
  consentLegalReviewRequired?: T;
  status?: T;
  pauseReason?: T;
  pausedAt?: T;
  pausedBy?: T;
  closeReason?: T;
  closedAt?: T;
  closedBy?: T;
  collectedAmount?: T;
  coverImagePath?: T;
  coverImageAlt?: T;
  code?: T;
  image?: T;
  category?: T;
  currency?: T;
  reportingMode?: T;
  isDonationOpen?: T;
  slug?: T;
  donorCount?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-categories_select".
 */
export interface NewsCategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  slug?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  image?: T;
  category?: T;
  newsCategory?: T;
  availableLocales?: T;
  excerpt?: T;
  contentBlocks?: T;
  tags?: T;
  searchText?: T;
  readTimeMinutes?: T;
  coverImagePath?: T;
  coverImageAlt?: T;
  relatedCampaigns?: T;
  status?: T;
  featured?: T;
  sortOrder?: T;
  viewCount?: T;
  publishedAt?: T;
  slug?: T;
  author?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  slug?: T;
  published?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "panel-settings_select".
 */
export interface PanelSettingsSelect<T extends boolean = true> {
  quickLinks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-intents_select".
 */
export interface DonationIntentsSelect<T extends boolean = true> {
  conversationId?: T;
  donorName?: T;
  email?: T;
  phone?: T;
  address?: T;
  city?: T;
  countryCode?: T;
  campaign?: T;
  quantity?: T;
  unitPriceSnapshot?: T;
  amount?: T;
  currency?: T;
  status?: T;
  paymentMethod?: T;
  reservationExpiresAt?: T;
  note?: T;
  taxReceiptRequested?: T;
  kvkkAcceptedAt?: T;
  termsAcceptedAt?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-participants_select".
 */
export interface DonationParticipantsSelect<T extends boolean = true> {
  donationIntent?: T;
  donation?: T;
  orderIndex?: T;
  name?: T;
  phone?: T;
  effectivePhone?: T;
  isPayer?: T;
  contactConsent?: T;
  proxyConsent?: T;
  nameReadingConsent?: T;
  nameReadingConsentTextVersion?: T;
  nameReadingConsentTextSnapshot?: T;
  nameReadingConsentAcceptedAt?: T;
  nameReadingConsentIp?: T;
  thirdPartyDataAuthorityConsent?: T;
  thirdPartyDataAuthorityTextVersion?: T;
  thirdPartyDataAuthorityTextSnapshot?: T;
  thirdPartyDataAuthorityAcceptedAt?: T;
  thirdPartyDataAuthorityIp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-sessions_select".
 */
export interface PaymentSessionsSelect<T extends boolean = true> {
  donationIntent?: T;
  conversationId?: T;
  paymentMethod?: T;
  reservationExpiresAt?: T;
  checkoutToken?: T;
  checkoutFormContent?: T;
  paymentPageUrl?: T;
  providerStatus?: T;
  fraudStatus?: T;
  paymentId?: T;
  lastFourDigits?: T;
  cardAssociation?: T;
  eftProofBucket?: T;
  eftProofPath?: T;
  eftReviewStatus?: T;
  eftReviewedAt?: T;
  eftReviewedBy?: T;
  rawResponse?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-events_select".
 */
export interface PaymentEventsSelect<T extends boolean = true> {
  eventType?: T;
  referenceId?: T;
  headers?: T;
  payload?: T;
  signatureVerified?: T;
  processedAt?: T;
  paymentSession?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations_select".
 */
export interface DonationsSelect<T extends boolean = true> {
  donorName?: T;
  email?: T;
  phone?: T;
  campaign?: T;
  donationIntent?: T;
  quantity?: T;
  unitPriceSnapshot?: T;
  grossAmount?: T;
  netConfirmedAmount?: T;
  currency?: T;
  status?: T;
  paymentId?: T;
  receiptNumber?: T;
  paymentSession?: T;
  paymentMethod?: T;
  confirmedAt?: T;
  taxReceiptRequested?: T;
  donationNote?: T;
  receiptPath?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operation-groups_select".
 */
export interface OperationGroupsSelect<T extends boolean = true> {
  campaign?: T;
  code?: T;
  operationType?: T;
  year?: T;
  ordinal?: T;
  capacity?: T;
  reservedCount?: T;
  confirmedCount?: T;
  status?: T;
  capacityOverrideOriginal?: T;
  capacityOverrideReason?: T;
  capacityOverrideCoveredByAssociation?: T;
  capacityOverriddenAt?: T;
  capacityOverriddenBy?: T;
  slaughterScheduledAt?: T;
  slaughterOrder?: T;
  slaughterPlace?: T;
  assignedOperator?: T;
  fieldNotes?: T;
  slaughteredAt?: T;
  slaughteredBy?: T;
  slaughterRevertedAt?: T;
  slaughterRevertedBy?: T;
  slaughterRevertReason?: T;
  slaughterScriptSnapshot?: T;
  groupCodeConfirmationFailures?: T;
  groupCodeLockedUntil?: T;
  activeVideo?: T;
  publicLinkTokenHash?: T;
  accessCodeHash?: T;
  accessCodeCiphertext?: T;
  accessCodeRotatedAt?: T;
  accessCodeRotatedBy?: T;
  accessCodeRotationCount?: T;
  expiresAt?: T;
  extensionUsed?: T;
  extendedAt?: T;
  extendedBy?: T;
  testMessageVideo?: T;
  testMessageFingerprint?: T;
  testMessagePassedAt?: T;
  testMessagePassedBy?: T;
  testMessageInvalidatedAt?: T;
  messageTemplate?: T;
  dispatchState?: T;
  dispatchLockedAt?: T;
  dispatchLockedBy?: T;
  dispatchPauseReason?: T;
  providerHealthySince?: T;
  providerHealthCheckCount?: T;
  consecutiveSystemFailures?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operation-group-members_select".
 */
export interface OperationGroupMembersSelect<T extends boolean = true> {
  group?: T;
  donationIntent?: T;
  donation?: T;
  participant?: T;
  memberKey?: T;
  unitIndex?: T;
  status?: T;
  reservationExpiresAt?: T;
  confirmedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operation-videos_select".
 */
export interface OperationVideosSelect<T extends boolean = true> {
  group?: T;
  uploadedBy?: T;
  uploadId?: T;
  rawStorageKey?: T;
  processedStorageKey?: T;
  thumbnailStorageKey?: T;
  originalFilename?: T;
  mimeType?: T;
  sizeBytes?: T;
  durationSeconds?: T;
  status?: T;
  version?: T;
  replacesVideo?: T;
  versionKind?: T;
  isActive?: T;
  uploadTokenJti?: T;
  uploadNonceHash?: T;
  uploadTokenExpiresAt?: T;
  uploadTokenConsumedAt?: T;
  uploadMaxBytes?: T;
  detectedMimeType?: T;
  containerFormat?: T;
  videoCodec?: T;
  audioCodec?: T;
  width?: T;
  height?: T;
  rawSha256?: T;
  processedSha256?: T;
  technicalMetadata?: T;
  processingSettingsSnapshot?: T;
  watermarkSnapshot?: T;
  closingCardSnapshot?: T;
  slaughterScriptSnapshot?: T;
  fieldChecklist?: T;
  fieldCheckedAt?: T;
  fieldCheckedBy?: T;
  reviewChecklist?: T;
  reviewedAt?: T;
  reviewedBy?: T;
  contentReviewStatus?: T;
  readyAt?: T;
  attemptCount?: T;
  lastError?: T;
  lastErrorCode?: T;
  ffmpegLog?: T;
  processingStartedAt?: T;
  processingFailedAt?: T;
  retryAfter?: T;
  quarantineUntil?: T;
  rawDeleteAfter?: T;
  processedDeleteAfter?: T;
  expiresAt?: T;
  expiredAt?: T;
  physicalDeletedAt?: T;
  extensionUsed?: T;
  extendedAt?: T;
  extendedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-messages_select".
 */
export interface DeliveryMessagesSelect<T extends boolean = true> {
  group?: T;
  video?: T;
  donation?: T;
  participant?: T;
  member?: T;
  messageType?: T;
  recipientRole?: T;
  recipientPhone?: T;
  normalizedPhone?: T;
  recipientPhoneHash?: T;
  body?: T;
  bodySnapshot?: T;
  messageSnapshot?: T;
  systemPayloadSnapshot?: T;
  idempotencyKey?: T;
  status?: T;
  dispatchBatchId?: T;
  scheduledAt?: T;
  lockedAt?: T;
  lockedBy?: T;
  providerMessageId?: T;
  providerStatus?: T;
  providerPayload?: T;
  attemptCount?: T;
  lastError?: T;
  lastErrorCode?: T;
  retryClass?: T;
  nextRetryAt?: T;
  lastAttemptAt?: T;
  providerLookupAt?: T;
  accessTokenDigest?: T;
  expiresAt?: T;
  sentAt?: T;
  deliveredAt?: T;
  readAt?: T;
  failedAt?: T;
  manualSentAt?: T;
  manualSentBy?: T;
  manualSentReason?: T;
  isTest?: T;
  testNumberKey?: T;
  testFingerprint?: T;
  redactedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-fulfillments_select".
 */
export interface DonationFulfillmentsSelect<T extends boolean = true> {
  donation?: T;
  status?: T;
  receiptStatus?: T;
  reportStatus?: T;
  emailStatus?: T;
  attemptCount?: T;
  lastAttemptAt?: T;
  lastError?: T;
  emailMessageId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refund-requests_select".
 */
export interface RefundRequestsSelect<T extends boolean = true> {
  donation?: T;
  type?: T;
  reason?: T;
  description?: T;
  evidenceBucket?: T;
  evidencePath?: T;
  evidenceMimeType?: T;
  manualReviewRequired?: T;
  amount?: T;
  providerReference?: T;
  providerResponse?: T;
  status?: T;
  requestedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  actorEmail?: T;
  targetCollection?: T;
  targetId?: T;
  details?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
