import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#1a1c1b",
        "primary-container": "#DCE9DF",
        "on-secondary-fixed-variant": "#65420F",
        "on-error": "#ffffff",
        "tertiary-fixed": "#e4e2e1",
        "on-secondary-container": "#3E2A12",
        "inverse-on-surface": "#f1f1ef",
        "surface-dim": "#dadad8",
        error: "#ba1a1a",
        "secondary-fixed-dim": "#E1C792",
        primary: "#0E5A3A",
        "tertiary-fixed-dim": "#c8c6c6",
        "inverse-primary": "#A8D0B4",
        outline: "#71756A",
        "on-tertiary-fixed": "#1b1c1c",
        "surface-container-low": "#F8F3EA",
        "on-secondary-fixed": "#34200B",
        tertiary: "#484847",
        "on-primary": "#ffffff",
        "inverse-surface": "#2f3130",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#E9E1D4",
        "secondary-fixed": "#F1DEC0",
        surface: "#FFFCF7",
        "on-surface": "#20261F",
        "outline-variant": "#D8CEBF",
        "on-tertiary-fixed-variant": "#474747",
        "surface-container-highest": "#E9E1D4",
        "surface-container-high": "#F1EBE1",
        "on-primary-container": "#153D29",
        "primary-fixed": "#DCE9DF",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#dcd9d9",
        "on-surface-variant": "#4F5349",
        "on-primary-fixed": "#062D1B",
        "surface-tint": "#0E5A3A",
        "surface-container": "#F5EFE5",
        "surface-bright": "#FFFCF7",
        "tertiary-container": "#605f5f",
        "primary-fixed-dim": "#A8D0B4",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "secondary-container": "#F1DEC0",
        secondary: "#70481B",
        background: "#FFFCF7",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#0A4A2F",
        gold: "#AC780F",
      },
      borderRadius: {
        DEFAULT: "0.375rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        base: "8px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        gutter: "24px",
        "container-max": "1200px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "56px",
          { lineHeight: "1.05", letterSpacing: "-0.025em", fontWeight: "700" },
        ],
        "display-lg-mobile": [
          "36px",
          { lineHeight: "1.15", letterSpacing: "-0.015em", fontWeight: "700" },
        ],
        "headline-xl": [
          "36px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-xl-mobile": [
          "28px",
          { lineHeight: "1.25", fontWeight: "600" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "1.3", letterSpacing: "-0.005em", fontWeight: "600" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "1.7", letterSpacing: "0.005em", fontWeight: "400" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "1.7", letterSpacing: "0.005em", fontWeight: "400" },
        ],
        "label-md": [
          "14px",
          {
            lineHeight: "1.5",
            letterSpacing: "0.01em",
            fontWeight: "500",
          },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "1.5", letterSpacing: "0.02em", fontWeight: "600" },
        ],
      },
      maxWidth: {
        "container-max": "1200px",
      },
      boxShadow: {
        soft: "0px 2px 12px rgba(0,0,0,0.04)",
        ambient: "0px 8px 30px rgba(14, 90, 58, 0.12)",
        "red-ambient": "0px 8px 30px rgba(14, 90, 58, 0.12)",
        elevated: "0px 4px 16px rgba(0,0,0,0.06)",
        "elevated-hover": "0px 8px 24px rgba(0,0,0,0.1)",
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-left": {
          "0%": { opacity: "0", transform: "translateX(-30px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "fade-right": {
          "0%": { opacity: "0", transform: "translateX(30px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "image-reveal": {
          "0%": { opacity: "0", transform: "scale(1.05)", filter: "blur(10px)" },
          "100%": { opacity: "1", transform: "scale(1)", filter: "blur(0)" },
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.6s ease-out",
        "fade-up": "fade-up 0.7s cubic-bezier(0.16, 1, 0.3, 1) both",
        "fade-left": "fade-left 0.7s cubic-bezier(0.16, 1, 0.3, 1) both",
        "fade-right": "fade-right 0.7s cubic-bezier(0.16, 1, 0.3, 1) both",
        "scale-in": "scale-in 0.6s cubic-bezier(0.16, 1, 0.3, 1) both",
        "image-reveal": "image-reveal 0.9s cubic-bezier(0.16, 1, 0.3, 1) both",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
export default config;
