import type { CollectionConfig } from "payload";

import { fieldOperatorOrAdmin } from "@/payload/access";

export const OperationVideos: CollectionConfig = {
  slug: "operation-videos",
  admin: {
    useAsTitle: "uploadId",
    group: "Video Teslimat",
    defaultColumns: ["uploadId", "group", "status", "version", "readyAt"],
  },
  access: {
    read: fieldOperatorOrAdmin,
    create: () => false,
    update: () => false,
    delete: () => false,
  },
  timestamps: true,
  fields: [
    { name: "group", type: "relationship", relationTo: "operation-groups", required: true, index: true },
    { name: "uploadedBy", type: "relationship", relationTo: "users", required: true, index: true },
    { name: "uploadId", type: "text", required: true, unique: true, index: true },
    {
      name: "rawStorageKey",
      type: "text",
      required: true,
      admin: { hidden: true },
      access: {
        read: ({ req }) => req.user?.role === "admin",
        update: () => false,
      },
    },
    {
      name: "processedStorageKey",
      type: "text",
      admin: { hidden: true },
      access: {
        read: ({ req }) => req.user?.role === "admin",
        update: () => false,
      },
    },
    {
      name: "thumbnailStorageKey",
      type: "text",
      admin: { hidden: true },
      access: {
        read: ({ req }) => req.user?.role === "admin",
        update: () => false,
      },
    },
    { name: "originalFilename", type: "text", required: true, access: { update: () => false } },
    { name: "mimeType", type: "text", required: true, access: { update: () => false } },
    { name: "sizeBytes", type: "number", required: true, min: 1, max: 2147483648, access: { update: () => false } },
    { name: "durationSeconds", type: "number", min: 0, max: 600, access: { update: () => false } },
    {
      name: "status",
      type: "select",
      required: true,
      defaultValue: "uploading",
      index: true,
      options: [
        "uploading",
        "uploaded",
        "processing",
        "review_pending",
        "ready",
        "superseded",
        "rejected",
        "failed",
        "processing_failed",
        "quarantined",
        "expired",
        "deleted",
      ],
    },
    { name: "version", type: "number", required: true, min: 1, defaultValue: 1 },
    { name: "replacesVideo", type: "relationship", relationTo: "operation-videos", index: true },
    {
      name: "versionKind",
      type: "select",
      required: true,
      defaultValue: "initial",
      options: ["initial", "replacement", "correction"],
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "isActive",
      type: "checkbox",
      required: true,
      defaultValue: false,
      index: true,
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "uploadTokenJti",
      type: "text",
      unique: true,
      index: true,
      admin: { hidden: true },
      access: { read: () => false, update: () => false },
    },
    {
      name: "uploadNonceHash",
      type: "text",
      unique: true,
      index: true,
      admin: { hidden: true },
      access: { read: () => false, update: () => false },
    },
    {
      name: "uploadTokenExpiresAt",
      type: "date",
      admin: { hidden: true },
      access: { read: () => false, update: () => false },
    },
    {
      name: "uploadTokenConsumedAt",
      type: "date",
      admin: { hidden: true },
      access: { read: () => false, update: () => false },
    },
    {
      name: "uploadMaxBytes",
      type: "number",
      required: true,
      defaultValue: 2147483648,
      min: 1,
      max: 2147483648,
      admin: { hidden: true },
      access: { read: () => false, update: () => false },
    },
    { name: "detectedMimeType", type: "text", admin: { readOnly: true }, access: { update: () => false } },
    { name: "containerFormat", type: "text", admin: { readOnly: true }, access: { update: () => false } },
    { name: "videoCodec", type: "text", admin: { readOnly: true }, access: { update: () => false } },
    { name: "audioCodec", type: "text", admin: { readOnly: true }, access: { update: () => false } },
    { name: "width", type: "number", min: 1, admin: { readOnly: true }, access: { update: () => false } },
    { name: "height", type: "number", min: 1, admin: { readOnly: true }, access: { update: () => false } },
    { name: "rawSha256", type: "text", index: true, admin: { readOnly: true }, access: { update: () => false } },
    { name: "processedSha256", type: "text", admin: { readOnly: true }, access: { update: () => false } },
    { name: "technicalMetadata", type: "json", admin: { readOnly: true }, access: { update: () => false } },
    { name: "processingSettingsSnapshot", type: "json", admin: { readOnly: true }, access: { update: () => false } },
    { name: "watermarkSnapshot", type: "json", admin: { readOnly: true }, access: { update: () => false } },
    { name: "closingCardSnapshot", type: "json", admin: { readOnly: true }, access: { update: () => false } },
    { name: "slaughterScriptSnapshot", type: "textarea", admin: { readOnly: true }, access: { update: () => false } },
    {
      name: "fieldChecklist",
      type: "json",
      required: true,
      defaultValue: {},
      admin: {
        description: "Saha görevlisinin içerik kontrol beyanlarıdır; otomatik içerik doğrulaması değildir.",
      },
    },
    { name: "fieldCheckedAt", type: "date", admin: { readOnly: true }, access: { update: () => false } },
    {
      name: "fieldCheckedBy",
      type: "relationship",
      relationTo: "users",
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "reviewChecklist",
      type: "json",
      required: true,
      defaultValue: {},
      admin: {
        description: "İşlenmiş video için insan tarafından tamamlanan son kontrol listesi.",
      },
    },
    { name: "reviewedAt", type: "date", admin: { readOnly: true }, access: { update: () => false } },
    {
      name: "reviewedBy",
      type: "relationship",
      relationTo: "users",
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "contentReviewStatus",
      type: "select",
      required: true,
      defaultValue: "pending",
      options: ["pending", "approved", "rejected"],
      admin: { readOnly: true },
      access: { update: () => false },
    },
    { name: "readyAt", type: "date" },
    { name: "attemptCount", type: "number", required: true, min: 0, defaultValue: 0 },
    { name: "lastError", type: "textarea" },
    { name: "lastErrorCode", type: "text", admin: { readOnly: true }, access: { update: () => false } },
    {
      name: "ffmpegLog",
      type: "textarea",
      admin: { readOnly: true },
      access: {
        read: ({ req }) => req.user?.role === "admin",
        update: () => false,
      },
    },
    { name: "processingStartedAt", type: "date", admin: { readOnly: true }, access: { update: () => false } },
    { name: "processingFailedAt", type: "date", admin: { readOnly: true }, access: { update: () => false } },
    { name: "retryAfter", type: "date", admin: { readOnly: true }, access: { update: () => false } },
    { name: "quarantineUntil", type: "date", index: true, admin: { readOnly: true }, access: { update: () => false } },
    { name: "rawDeleteAfter", type: "date", required: true, index: true },
    { name: "processedDeleteAfter", type: "date", required: true, index: true },
    { name: "expiresAt", type: "date", index: true, admin: { readOnly: true }, access: { update: () => false } },
    { name: "expiredAt", type: "date", index: true, admin: { readOnly: true }, access: { update: () => false } },
    { name: "physicalDeletedAt", type: "date", index: true, admin: { readOnly: true }, access: { update: () => false } },
    {
      name: "extensionUsed",
      type: "checkbox",
      required: true,
      defaultValue: false,
      admin: { readOnly: true },
      access: { update: () => false },
    },
    { name: "extendedAt", type: "date", admin: { readOnly: true }, access: { update: () => false } },
    {
      name: "extendedBy",
      type: "relationship",
      relationTo: "users",
      admin: { readOnly: true },
      access: { update: () => false },
    },
  ],
};
