import type { CollectionConfig } from "payload";

import { fieldOperatorOrAdmin } from "@/payload/access";

export const OperationGroups: CollectionConfig = {
  slug: "operation-groups",
  admin: {
    useAsTitle: "code",
    group: "Video Teslimat",
    defaultColumns: ["code", "campaign", "status", "dispatchState", "reservedCount", "confirmedCount"],
  },
  access: {
    read: fieldOperatorOrAdmin,
    create: () => false,
    update: () => false,
    delete: () => false,
  },
  timestamps: true,
  fields: [
    { name: "campaign", type: "relationship", relationTo: "campaigns", required: true, index: true },
    { name: "code", type: "text", required: true, unique: true, index: true },
    {
      name: "operationType",
      type: "select",
      options: [
        { label: "Standart video", value: "standard_video" },
        { label: "Kesim videosu", value: "slaughter_video" },
      ],
      admin: { readOnly: true },
      access: { update: () => false },
    },
    { name: "year", type: "number", required: true, min: 2020, index: true },
    { name: "ordinal", type: "number", required: true, min: 1 },
    { name: "capacity", type: "number", min: 1 },
    { name: "reservedCount", type: "number", required: true, min: 0, defaultValue: 0, admin: { readOnly: true } },
    { name: "confirmedCount", type: "number", required: true, min: 0, defaultValue: 0, admin: { readOnly: true } },
    {
      name: "status",
      type: "select",
      required: true,
      defaultValue: "collecting",
      index: true,
      options: [
        { label: "Toplanıyor", value: "collecting" },
        { label: "Dolu", value: "full" },
        { label: "Kesime hazır", value: "ready_for_slaughter" },
        { label: "Kesim planlandı", value: "scheduled" },
        { label: "Kesildi", value: "slaughtered" },
        { label: "Video bekliyor", value: "video_pending" },
        { label: "Video hazır", value: "video_ready" },
        { label: "Teslimat başladı", value: "delivery_started" },
        { label: "Tamamlandı", value: "completed" },
        { label: "Açık (eski kayıt)", value: "open" },
        { label: "Bildirildi (eski kayıt)", value: "notified" },
        { label: "Kapalı (eski kayıt)", value: "closed" },
        { label: "İşlem gerekli", value: "action_required" },
      ],
    },
    {
      name: "capacityOverrideOriginal",
      type: "number",
      min: 1,
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "capacityOverrideReason",
      type: "textarea",
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "capacityOverrideCoveredByAssociation",
      type: "checkbox",
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "capacityOverriddenAt",
      type: "date",
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "capacityOverriddenBy",
      type: "relationship",
      relationTo: "users",
      admin: { readOnly: true },
      access: { update: () => false },
    },
    { name: "slaughterScheduledAt", type: "date", index: true },
    { name: "slaughterOrder", type: "number", min: 1 },
    { name: "slaughterPlace", type: "text" },
    { name: "assignedOperator", type: "relationship", relationTo: "users", index: true },
    { name: "fieldNotes", type: "textarea" },
    {
      name: "slaughteredAt",
      type: "date",
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "slaughteredBy",
      type: "relationship",
      relationTo: "users",
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "slaughterRevertedAt",
      type: "date",
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "slaughterRevertedBy",
      type: "relationship",
      relationTo: "users",
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "slaughterRevertReason",
      type: "textarea",
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "slaughterScriptSnapshot",
      type: "textarea",
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "groupCodeConfirmationFailures",
      type: "number",
      required: true,
      defaultValue: 0,
      min: 0,
      max: 3,
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "groupCodeLockedUntil",
      type: "date",
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "activeVideo",
      type: "relationship",
      relationTo: "operation-videos",
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "publicLinkTokenHash",
      type: "text",
      unique: true,
      index: true,
      admin: { hidden: true },
      access: { read: () => false, update: () => false },
    },
    {
      name: "accessCodeHash",
      type: "text",
      admin: { hidden: true },
      access: { read: () => false, update: () => false },
    },
    {
      name: "accessCodeCiphertext",
      type: "textarea",
      admin: { hidden: true },
      access: { read: () => false, update: () => false },
    },
    {
      name: "accessCodeRotatedAt",
      type: "date",
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "accessCodeRotatedBy",
      type: "relationship",
      relationTo: "users",
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "accessCodeRotationCount",
      type: "number",
      required: true,
      defaultValue: 0,
      min: 0,
      admin: { readOnly: true },
      access: { update: () => false },
    },
    { name: "expiresAt", type: "date", index: true, admin: { readOnly: true }, access: { update: () => false } },
    {
      name: "extensionUsed",
      type: "checkbox",
      required: true,
      defaultValue: false,
      admin: { readOnly: true },
      access: { update: () => false },
    },
    { name: "extendedAt", type: "date", admin: { readOnly: true }, access: { update: () => false } },
    {
      name: "extendedBy",
      type: "relationship",
      relationTo: "users",
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "testMessageVideo",
      type: "relationship",
      relationTo: "operation-videos",
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "testMessageFingerprint",
      type: "text",
      admin: { hidden: true },
      access: { read: () => false, update: () => false },
    },
    { name: "testMessagePassedAt", type: "date", admin: { readOnly: true }, access: { update: () => false } },
    {
      name: "testMessagePassedBy",
      type: "relationship",
      relationTo: "users",
      admin: { readOnly: true },
      access: { update: () => false },
    },
    { name: "testMessageInvalidatedAt", type: "date", admin: { readOnly: true }, access: { update: () => false } },
    { name: "messageTemplate", type: "textarea", required: true },
    {
      name: "dispatchState",
      type: "select",
      required: true,
      defaultValue: "idle",
      index: true,
      options: ["idle", "countdown", "queued", "sending", "paused", "completed", "cancelled", "failed"],
    },
    { name: "dispatchLockedAt", type: "date", index: true },
    { name: "dispatchLockedBy", type: "text" },
    { name: "dispatchPauseReason", type: "textarea", admin: { readOnly: true }, access: { update: () => false } },
    { name: "providerHealthySince", type: "date", admin: { readOnly: true }, access: { update: () => false } },
    {
      name: "providerHealthCheckCount",
      type: "number",
      required: true,
      defaultValue: 0,
      min: 0,
      admin: { readOnly: true },
      access: { update: () => false },
    },
    {
      name: "consecutiveSystemFailures",
      type: "number",
      required: true,
      defaultValue: 0,
      min: 0,
      admin: { readOnly: true },
      access: { update: () => false },
    },
  ],
};
