import type { CollectionConfig } from "payload";

import { superAdminsOnly } from "@/payload/access";

export const QurbaniOrders: CollectionConfig = {
  slug: "qurbani-orders",
  admin: {
    useAsTitle: "orderNumber",
    group: "Kurban",
    defaultColumns: ["orderNumber", "buyerName", "product", "shareCount", "totalAmount", "status", "reservedUntil"],
    listSearchableFields: ["orderNumber", "buyerName", "buyerEmail", "buyerPhone", "providerPaymentId"],
  },
  access: { read: superAdminsOnly, create: () => false, update: () => false, delete: () => false },
  timestamps: true,
  fields: [
    { name: "orderNumber", type: "text", required: true, unique: true, index: true },
    { name: "season", type: "relationship", relationTo: "qurbani-seasons", required: true, index: true },
    { name: "product", type: "relationship", relationTo: "qurbani-products", required: true, index: true },
    { name: "pool", type: "relationship", relationTo: "qurbani-pools", index: true },
    { name: "checkout", type: "relationship", relationTo: "qurbani-checkouts", index: true },
    { name: "checkoutLine", type: "relationship", relationTo: "qurbani-checkout-lines", index: true },
    { name: "priceRevision", type: "relationship", relationTo: "qurbani-price-revisions", index: true },
    { name: "donationIntent", type: "relationship", relationTo: "donation-intents", index: true },
    { name: "donation", type: "relationship", relationTo: "donations", index: true },
    { name: "buyerName", type: "text", required: true },
    { name: "buyerEmail", type: "email", required: true },
    { name: "buyerPhone", type: "text", required: true },
    { name: "countryCode", type: "text", required: true, defaultValue: "TR" },
    { name: "identityType", type: "select", options: ["tc_identity", "passport", "national_identity"] },
    { name: "identityNumber", type: "text" },
    { name: "addressSnapshot", type: "json" },
    { name: "productSnapshot", type: "json", required: true },
    { name: "unitPrice", type: "number", required: true, min: 0 },
    { name: "shareCount", type: "number", required: true, min: 1, max: 7 },
    { name: "totalAmount", type: "number", required: true, min: 0 },
    { name: "currency", type: "select", required: true, options: ["TRY", "USD", "EUR", "GBP"] },
    { name: "paymentMethod", type: "select", required: true, options: ["iyzico", "eft"] },
    { name: "reservationKind", type: "select", required: true, options: ["iyzico", "eft"] },
    {
      name: "status", type: "select", required: true, defaultValue: "reserved", index: true,
      options: ["reserved", "pending_payment", "pending_eft_review", "paid", "failed", "expired", "cancelled", "action_required", "refunded"],
    },
    { name: "reservedUntil", type: "date", required: true, index: true },
    { name: "providerPaymentId", type: "text", index: true },
    { name: "providerReference", type: "text" },
    { name: "eftProofBucket", type: "text" },
    { name: "eftProofPath", type: "text" },
    { name: "eftProofMimeType", type: "text" },
    { name: "eftReviewedAt", type: "date" },
    { name: "eftReviewedBy", type: "relationship", relationTo: "users" },
    { name: "proxyTextVersion", type: "text", required: true },
    { name: "proxyAcceptedAt", type: "date", required: true },
    { name: "proxyAcceptedIp", type: "text", required: true },
    { name: "phoneProxyConfirmedAt", type: "date" },
    { name: "phoneProxyConfirmedBy", type: "relationship", relationTo: "users" },
    { name: "kvkkAcceptedAt", type: "date", required: true },
    { name: "termsAcceptedAt", type: "date", required: true },
    { name: "thirdPartyContactConsentAt", type: "date" },
    { name: "paidAt", type: "date" },
    { name: "failureReason", type: "textarea" },
    { name: "isLegacy", type: "checkbox", required: true, defaultValue: false },
  ],
};
