begin;

alter table public.categories add column if not exists sort_order integer default 0 not null;
alter table public.categories add column if not exists is_active boolean default true not null;
alter table public.categories_locales add column if not exists description character varying default ''::character varying;

create table if not exists public.news_categories (
  id integer generated by default as identity primary key,
  slug character varying not null,
  sort_order integer default 0 not null,
  is_active boolean default true not null,
  updated_at timestamp(3) with time zone default now() not null,
  created_at timestamp(3) with time zone default now() not null
);

create table if not exists public.news_categories_locales (
  name character varying not null,
  description character varying default ''::character varying,
  id integer generated by default as identity primary key,
  _locale public._locales not null,
  _parent_id integer not null references public.news_categories(id) on delete cascade
);

create unique index if not exists news_categories_slug_idx on public.news_categories (slug);
create index if not exists news_categories_sort_order_idx on public.news_categories (sort_order);
create index if not exists news_categories_updated_at_idx on public.news_categories (updated_at);
create unique index if not exists news_categories_locales_locale_parent_id_unique on public.news_categories_locales (_locale, _parent_id);

insert into public.news_categories (slug, sort_order, is_active)
values ('haber', 0, true), ('etkinlik', 10, true), ('duyuru', 20, true), ('proje', 30, true)
on conflict (slug) do nothing;

insert into public.news_categories_locales (name, description, _locale, _parent_id)
select values_table.name, values_table.description, values_table.locale::public._locales, category.id
from (values
  ('haber', 'Haber', 'Dernekten güncel haberler', 'tr'), ('haber', 'News', 'Latest association news', 'en'), ('haber', 'الأخبار', 'آخر أخبار الجمعية', 'ar'),
  ('etkinlik', 'Etkinlik', 'Etkinlik ve buluşmalar', 'tr'), ('etkinlik', 'Events', 'Events and meetings', 'en'), ('etkinlik', 'الفعاليات', 'الفعاليات واللقاءات', 'ar'),
  ('duyuru', 'Duyuru', 'Önemli duyurular', 'tr'), ('duyuru', 'Announcements', 'Important announcements', 'en'), ('duyuru', 'الإعلانات', 'إعلانات مهمة', 'ar'),
  ('proje', 'Proje', 'Sahadaki projeler', 'tr'), ('proje', 'Projects', 'Projects in the field', 'en'), ('proje', 'المشاريع', 'المشاريع الميدانية', 'ar')
) as values_table(slug, name, description, locale)
join public.news_categories category on category.slug = values_table.slug
on conflict (_locale, _parent_id) do nothing;

do $$ begin
  create type public.enum_news_status as enum ('draft', 'published', 'archived');
exception when duplicate_object then null;
end $$;

alter table public.news add column if not exists news_category_id integer;
alter table public.news add column if not exists cover_image_path character varying;
alter table public.news add column if not exists status public.enum_news_status default 'draft'::public.enum_news_status not null;
alter table public.news add column if not exists featured boolean default false not null;
alter table public.news add column if not exists sort_order integer default 0 not null;
alter table public.news add column if not exists view_count numeric default 0 not null;

alter table public.news_locales add column if not exists excerpt character varying;
alter table public.news_locales add column if not exists content_blocks jsonb default '[]'::jsonb;
alter table public.news_locales add column if not exists tags jsonb default '[]'::jsonb;
alter table public.news_locales add column if not exists search_text character varying;
alter table public.news_locales add column if not exists read_time_minutes numeric default 1;
alter table public.news_locales add column if not exists cover_image_alt character varying;

update public.news
set status = case when published_at is null then 'draft'::public.enum_news_status else 'published'::public.enum_news_status end,
    news_category_id = coalesce(news_category_id, (select id from public.news_categories where slug = public.news.category::text limit 1));

update public.news_locales
set excerpt = coalesce(nullif(excerpt, ''), left(title, 240)),
    cover_image_alt = coalesce(nullif(cover_image_alt, ''), title),
    search_text = coalesce(nullif(search_text, ''), title || ' ' || coalesce(excerpt, '')),
    read_time_minutes = greatest(coalesce(read_time_minutes, 1), 1);

do $$ begin
  alter table public.news add constraint news_news_category_id_news_categories_id_fk foreign key (news_category_id) references public.news_categories(id) on delete set null;
exception when duplicate_object then null;
end $$;

create index if not exists news_news_category_idx on public.news (news_category_id);
create index if not exists news_status_published_at_idx on public.news (status, published_at desc);
create index if not exists news_featured_status_idx on public.news (featured, status);

create table if not exists public.news_rels (
  id integer generated by default as identity primary key,
  "order" integer,
  parent_id integer not null references public.news(id) on delete cascade,
  path character varying not null,
  campaigns_id integer references public.campaigns(id) on delete cascade
);
create index if not exists news_rels_order_idx on public.news_rels ("order");
create index if not exists news_rels_parent_idx on public.news_rels (parent_id);
create index if not exists news_rels_path_idx on public.news_rels (path);
create index if not exists news_rels_campaigns_id_idx on public.news_rels (campaigns_id);

alter table public.payload_locked_documents_rels add column if not exists news_categories_id integer;
do $$ begin
  alter table public.payload_locked_documents_rels add constraint payload_locked_documents_rels_news_categories_fk foreign key (news_categories_id) references public.news_categories(id) on delete cascade;
exception when duplicate_object then null;
end $$;
create index if not exists payload_locked_documents_rels_news_categories_id_idx on public.payload_locked_documents_rels (news_categories_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('news-media', 'news-media', true, 10485760, array['image/jpeg','image/png','image/webp']::text[])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.increment_news_view_count(p_slug text)
returns void
language sql
security definer
set search_path = public
as $$
  update public.news set view_count = coalesce(view_count, 0) + 1 where slug = p_slug and status = 'published';
$$;
revoke all on function public.increment_news_view_count(text) from public, anon, authenticated;
grant execute on function public.increment_news_view_count(text) to service_role;

alter table public.news_categories enable row level security;
alter table public.news_categories_locales enable row level security;
alter table public.news_rels enable row level security;

commit;
