begin;

-- PanelSettings remains registered in Payload. A legacy-system cleanup
-- accidentally removed both its table and its document-lock relation.
create table if not exists public.panel_settings (
  id integer generated by default as identity primary key,
  quick_links jsonb not null default '[]'::jsonb,
  updated_at timestamp(3) with time zone not null default now(),
  created_at timestamp(3) with time zone not null default now(),
  constraint panel_settings_singleton_check check (id = 1),
  constraint panel_settings_quick_links_array_check
    check (jsonb_typeof(quick_links) = 'array')
);

alter table public.panel_settings enable row level security;
revoke all on table public.panel_settings from anon, authenticated;

alter table public.payload_locked_documents_rels
  add column if not exists panel_settings_id integer;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.payload_locked_documents_rels'::regclass
      and conname = 'payload_locked_documents_rels_panel_settings_id_fkey'
  ) then
    alter table public.payload_locked_documents_rels
      add constraint payload_locked_documents_rels_panel_settings_id_fkey
      foreign key (panel_settings_id)
      references public.panel_settings(id)
      on delete cascade;
  end if;
end;
$$;

create index if not exists payload_locked_documents_rels_panel_settings_idx
  on public.payload_locked_documents_rels (panel_settings_id);

commit;
