begin;

create table if not exists public.panel_settings (
  id integer generated by default as identity primary key,
  quick_links jsonb not null default '[]'::jsonb,
  updated_at timestamp(3) with time zone not null default now(),
  created_at timestamp(3) with time zone not null default now(),
  constraint panel_settings_singleton_check check (id = 1),
  constraint panel_settings_quick_links_array_check check (jsonb_typeof(quick_links) = 'array')
);

alter table public.panel_settings enable row level security;
revoke all on table public.panel_settings from anon, authenticated;

commit;
