begin;

create schema if not exists private;

do $$
begin
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'enum_qurbani_seasons_status') then
    create type public.enum_qurbani_seasons_status as enum ('draft', 'active', 'sales_closed', 'completed', 'archived');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'enum_qurbani_products_kind') then
    create type public.enum_qurbani_products_kind as enum ('cattle', 'small_livestock');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'enum_qurbani_products_currency') then
    create type public.enum_qurbani_products_currency as enum ('TRY', 'USD', 'EUR', 'GBP');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'enum_qurbani_pools_status') then
    create type public.enum_qurbani_pools_status as enum ('open', 'full', 'assigned', 'in_progress', 'video_processing', 'ready', 'notified', 'closed');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'enum_qurbani_orders_identity_type') then
    create type public.enum_qurbani_orders_identity_type as enum ('tc_identity', 'passport', 'national_identity');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'enum_qurbani_orders_currency') then
    create type public.enum_qurbani_orders_currency as enum ('TRY', 'USD', 'EUR', 'GBP');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'enum_qurbani_orders_payment_method') then
    create type public.enum_qurbani_orders_payment_method as enum ('iyzico', 'eft');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'enum_qurbani_orders_reservation_kind') then
    create type public.enum_qurbani_orders_reservation_kind as enum ('iyzico', 'eft');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'enum_qurbani_orders_status') then
    create type public.enum_qurbani_orders_status as enum ('reserved', 'pending_payment', 'pending_eft_review', 'paid', 'failed', 'expired', 'cancelled', 'action_required', 'refunded');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'enum_qurbani_shares_status') then
    create type public.enum_qurbani_shares_status as enum ('reserved', 'confirmed', 'cancelled', 'action_required');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'enum_qurbani_videos_status') then
    create type public.enum_qurbani_videos_status as enum ('uploading', 'uploaded', 'processing', 'ready_for_review', 'approved', 'rejected', 'failed');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'enum_qurbani_messages_channel') then
    create type public.enum_qurbani_messages_channel as enum ('whatsapp', 'sms');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'enum_qurbani_messages_status') then
    create type public.enum_qurbani_messages_status as enum ('queued', 'sending', 'sent', 'delivered', 'read', 'failed', 'cancelled');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'enum_qurbani_jobs_type') then
    create type public.enum_qurbani_jobs_type as enum ('expire_reservations', 'process_video', 'purge_storage', 'send_whatsapp');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'enum_qurbani_jobs_status') then
    create type public.enum_qurbani_jobs_status as enum ('queued', 'processing', 'completed', 'failed', 'dead');
  end if;
end;
$$;

create table if not exists public.qurbani_seasons (
  id integer generated by default as identity primary key,
  year numeric not null,
  status public.enum_qurbani_seasons_status not null default 'draft',
  sales_start_at timestamp(3) with time zone not null,
  sales_end_at timestamp(3) with time zone not null,
  eid_at timestamp(3) with time zone not null,
  code_counter numeric not null default 0,
  available_locales jsonb not null default '["tr"]'::jsonb,
  hero_image_id integer references public.media(id) on delete set null,
  bank_name character varying,
  account_holder character varying,
  iban character varying,
  bank_branch character varying,
  proxy_text_version character varying not null default '1.0',
  updated_at timestamp(3) with time zone not null default now(),
  created_at timestamp(3) with time zone not null default now(),
  constraint qurbani_seasons_year_check check (year = trunc(year) and year between 2020 and 2200),
  constraint qurbani_seasons_code_counter_check check (code_counter = trunc(code_counter) and code_counter >= 0),
  constraint qurbani_seasons_sales_dates_check check (sales_start_at < sales_end_at)
);

create table if not exists public.qurbani_seasons_locales (
  hero_title character varying not null,
  hero_description character varying,
  page_content character varying,
  process_steps jsonb default '[]'::jsonb,
  eft_description character varying,
  proxy_text character varying not null,
  id integer generated by default as identity primary key,
  _locale public._locales not null,
  _parent_id integer not null references public.qurbani_seasons(id) on delete cascade
);

create table if not exists public.qurbani_products (
  id integer generated by default as identity primary key,
  season_id integer not null references public.qurbani_seasons(id) on delete restrict,
  campaign_id integer not null references public.campaigns(id) on delete restrict,
  funding_pool_id integer not null references public.campaign_funding_pools(id) on delete restrict,
  image_id integer references public.media(id) on delete set null,
  kind public.enum_qurbani_products_kind not null,
  price numeric not null,
  currency public.enum_qurbani_products_currency not null default 'TRY',
  capacity numeric not null default 7,
  sales_start_at timestamp(3) with time zone,
  sales_end_at timestamp(3) with time zone,
  sort_order numeric not null default 0,
  is_active boolean not null default true,
  updated_at timestamp(3) with time zone not null default now(),
  created_at timestamp(3) with time zone not null default now(),
  constraint qurbani_products_price_check check (price >= 0),
  constraint qurbani_products_capacity_check check (
    capacity = trunc(capacity)
    and ((kind = 'cattle' and capacity between 1 and 7) or (kind = 'small_livestock' and capacity = 1))
  ),
  constraint qurbani_products_sales_dates_check check (sales_start_at is null or sales_end_at is null or sales_start_at < sales_end_at)
);

create table if not exists public.qurbani_products_locales (
  title character varying not null,
  description character varying,
  region character varying not null,
  id integer generated by default as identity primary key,
  _locale public._locales not null,
  _parent_id integer not null references public.qurbani_products(id) on delete cascade
);

create table if not exists public.qurbani_pools (
  id integer generated by default as identity primary key,
  season_id integer not null references public.qurbani_seasons(id) on delete restrict,
  product_id integer not null references public.qurbani_products(id) on delete restrict,
  code character varying,
  capacity numeric not null,
  reserved_count numeric not null default 0,
  confirmed_count numeric not null default 0,
  status public.enum_qurbani_pools_status not null default 'open',
  field_task_id integer references public.field_tasks(id) on delete set null,
  full_at timestamp(3) with time zone,
  locked_at timestamp(3) with time zone,
  action_required boolean not null default false,
  operation_notes character varying,
  updated_at timestamp(3) with time zone not null default now(),
  created_at timestamp(3) with time zone not null default now(),
  constraint qurbani_pools_capacity_check check (capacity = trunc(capacity) and capacity between 1 and 7),
  constraint qurbani_pools_counts_check check (
    reserved_count = trunc(reserved_count) and confirmed_count = trunc(confirmed_count)
    and reserved_count >= 0 and confirmed_count >= 0
    and reserved_count + confirmed_count <= capacity
  ),
  constraint qurbani_pools_code_check check (code is null or code ~ '^MD-[0-9]{4}-[0-9]{4}$')
);

create table if not exists public.qurbani_orders (
  id integer generated by default as identity primary key,
  order_number character varying not null,
  season_id integer not null references public.qurbani_seasons(id) on delete restrict,
  product_id integer not null references public.qurbani_products(id) on delete restrict,
  pool_id integer references public.qurbani_pools(id) on delete restrict,
  donation_intent_id integer references public.donation_intents(id) on delete set null,
  donation_id integer references public.donations(id) on delete set null,
  buyer_name character varying not null,
  buyer_email character varying not null,
  buyer_phone character varying not null,
  country_code character varying not null default 'TR',
  identity_type public.enum_qurbani_orders_identity_type,
  identity_number character varying,
  address_snapshot jsonb,
  product_snapshot jsonb not null,
  unit_price numeric not null,
  share_count numeric not null,
  total_amount numeric not null,
  currency public.enum_qurbani_orders_currency not null,
  payment_method public.enum_qurbani_orders_payment_method not null,
  reservation_kind public.enum_qurbani_orders_reservation_kind not null,
  status public.enum_qurbani_orders_status not null default 'reserved',
  reserved_until timestamp(3) with time zone not null,
  provider_payment_id character varying,
  provider_reference character varying,
  eft_proof_bucket character varying,
  eft_proof_path character varying,
  eft_proof_mime_type character varying,
  eft_reviewed_at timestamp(3) with time zone,
  eft_reviewed_by_id integer references public.users(id) on delete set null,
  proxy_text_version character varying not null,
  proxy_accepted_at timestamp(3) with time zone not null,
  proxy_accepted_ip character varying not null,
  phone_proxy_confirmed_at timestamp(3) with time zone,
  phone_proxy_confirmed_by_id integer references public.users(id) on delete set null,
  kvkk_accepted_at timestamp(3) with time zone not null,
  terms_accepted_at timestamp(3) with time zone not null,
  third_party_contact_consent_at timestamp(3) with time zone,
  paid_at timestamp(3) with time zone,
  failure_reason character varying,
  updated_at timestamp(3) with time zone not null default now(),
  created_at timestamp(3) with time zone not null default now(),
  constraint qurbani_orders_amounts_check check (unit_price >= 0 and total_amount = unit_price * share_count),
  constraint qurbani_orders_share_count_check check (share_count = trunc(share_count) and share_count between 1 and 7),
  constraint qurbani_orders_country_code_check check (country_code ~ '^[A-Z]{2}$'),
  constraint qurbani_orders_eft_proof_check check (
    eft_proof_mime_type is null or eft_proof_mime_type in ('application/pdf', 'image/jpeg', 'image/png')
  )
);

create table if not exists public.qurbani_shares (
  id integer generated by default as identity primary key,
  order_id integer not null references public.qurbani_orders(id) on delete restrict,
  pool_id integer not null references public.qurbani_pools(id) on delete restrict,
  owner_name character varying not null,
  owner_phone character varying,
  effective_phone character varying not null,
  sequence numeric not null,
  status public.enum_qurbani_shares_status not null default 'reserved',
  confirmed_at timestamp(3) with time zone,
  updated_at timestamp(3) with time zone not null default now(),
  created_at timestamp(3) with time zone not null default now(),
  constraint qurbani_shares_sequence_check check (sequence = trunc(sequence) and sequence between 1 and 7),
  constraint qurbani_shares_owner_name_check check (length(btrim(owner_name)) > 0),
  constraint qurbani_shares_effective_phone_check check (length(btrim(effective_phone)) > 0)
);

create table if not exists public.qurbani_videos (
  id integer generated by default as identity primary key,
  pool_id integer not null references public.qurbani_pools(id) on delete restrict,
  field_task_id integer not null references public.field_tasks(id) on delete restrict,
  uploaded_by_id integer not null references public.users(id) on delete restrict,
  upload_id character varying not null,
  raw_storage_key character varying not null,
  processed_storage_key character varying,
  thumbnail_storage_key character varying,
  original_filename character varying not null,
  mime_type character varying not null,
  size_bytes numeric not null,
  duration_seconds numeric,
  status public.enum_qurbani_videos_status not null default 'uploaded',
  attempt_count numeric not null default 0,
  last_error character varying,
  approved_at timestamp(3) with time zone,
  approved_by_id integer references public.users(id) on delete set null,
  raw_delete_after timestamp(3) with time zone,
  processed_delete_after timestamp(3) with time zone,
  updated_at timestamp(3) with time zone not null default now(),
  created_at timestamp(3) with time zone not null default now(),
  constraint qurbani_videos_size_check check (size_bytes > 0 and size_bytes <= 1073741824),
  constraint qurbani_videos_duration_check check (duration_seconds is null or duration_seconds between 0 and 900),
  constraint qurbani_videos_attempt_count_check check (attempt_count = trunc(attempt_count) and attempt_count >= 0)
);

create table if not exists public.qurbani_access_links (
  id integer generated by default as identity primary key,
  pool_id integer not null references public.qurbani_pools(id) on delete restrict,
  order_id integer not null references public.qurbani_orders(id) on delete restrict,
  video_id integer not null references public.qurbani_videos(id) on delete restrict,
  token_digest character varying not null,
  recipient_phone character varying not null,
  recipient_phone_hash character varying not null,
  share_ids jsonb not null,
  expires_at timestamp(3) with time zone not null,
  revoked_at timestamp(3) with time zone,
  last_accessed_at timestamp(3) with time zone,
  access_count numeric not null default 0,
  updated_at timestamp(3) with time zone not null default now(),
  created_at timestamp(3) with time zone not null default now(),
  constraint qurbani_access_links_access_count_check check (access_count = trunc(access_count) and access_count >= 0)
);

create table if not exists public.qurbani_access_links_rels (
  id integer generated by default as identity primary key,
  "order" integer,
  parent_id integer not null references public.qurbani_access_links(id) on delete cascade,
  path character varying not null,
  qurbani_shares_id integer references public.qurbani_shares(id) on delete restrict
);

create table if not exists public.qurbani_messages (
  id integer generated by default as identity primary key,
  pool_id integer not null references public.qurbani_pools(id) on delete restrict,
  access_link_id integer not null references public.qurbani_access_links(id) on delete restrict,
  channel public.enum_qurbani_messages_channel not null default 'whatsapp',
  recipient_phone character varying not null,
  recipient_phone_hash character varying not null,
  share_summary jsonb not null,
  body character varying not null,
  idempotency_key character varying not null,
  status public.enum_qurbani_messages_status not null default 'queued',
  provider_message_id character varying,
  attempt_count numeric not null default 0,
  last_error character varying,
  sent_at timestamp(3) with time zone,
  delivered_at timestamp(3) with time zone,
  read_at timestamp(3) with time zone,
  updated_at timestamp(3) with time zone not null default now(),
  created_at timestamp(3) with time zone not null default now(),
  constraint qurbani_messages_attempt_count_check check (attempt_count = trunc(attempt_count) and attempt_count >= 0),
  constraint qurbani_messages_sms_disabled_check check (channel <> 'sms' or status = 'cancelled')
);

create table if not exists public.qurbani_jobs (
  id integer generated by default as identity primary key,
  type public.enum_qurbani_jobs_type not null,
  status public.enum_qurbani_jobs_status not null default 'queued',
  order_id integer references public.qurbani_orders(id) on delete cascade,
  pool_id integer references public.qurbani_pools(id) on delete cascade,
  video_id integer references public.qurbani_videos(id) on delete cascade,
  message_id integer references public.qurbani_messages(id) on delete cascade,
  payload jsonb,
  idempotency_key character varying,
  run_at timestamp(3) with time zone not null default now(),
  locked_at timestamp(3) with time zone,
  locked_by character varying,
  attempt_count numeric not null default 0,
  max_attempts numeric not null default 5,
  last_error character varying,
  completed_at timestamp(3) with time zone,
  updated_at timestamp(3) with time zone not null default now(),
  created_at timestamp(3) with time zone not null default now(),
  constraint qurbani_jobs_attempts_check check (
    attempt_count = trunc(attempt_count) and max_attempts = trunc(max_attempts)
    and attempt_count >= 0 and max_attempts >= 1
  )
);

alter table public.donation_intents add column if not exists qurbani_order_id integer;
alter table public.donations add column if not exists qurbani_order_id integer;
alter table public.field_tasks add column if not exists qurbani_pool_id integer;

do $$ begin
  alter table public.donation_intents add constraint donation_intents_qurbani_order_id_fk
    foreign key (qurbani_order_id) references public.qurbani_orders(id) on delete set null;
exception when duplicate_object then null; end $$;
do $$ begin
  alter table public.donations add constraint donations_qurbani_order_id_fk
    foreign key (qurbani_order_id) references public.qurbani_orders(id) on delete set null;
exception when duplicate_object then null; end $$;
do $$ begin
  alter table public.field_tasks add constraint field_tasks_qurbani_pool_id_fk
    foreign key (qurbani_pool_id) references public.qurbani_pools(id) on delete set null;
exception when duplicate_object then null; end $$;

create unique index if not exists qurbani_seasons_year_idx on public.qurbani_seasons(year);
create unique index if not exists qurbani_seasons_single_active_idx on public.qurbani_seasons(status) where status = 'active';
create index if not exists qurbani_seasons_status_sales_idx on public.qurbani_seasons(status, sales_start_at, sales_end_at);
create index if not exists qurbani_seasons_hero_image_idx on public.qurbani_seasons(hero_image_id);
create index if not exists qurbani_seasons_updated_at_idx on public.qurbani_seasons(updated_at);
create unique index if not exists qurbani_seasons_locales_parent_locale_idx on public.qurbani_seasons_locales(_parent_id, _locale);

create index if not exists qurbani_products_season_idx on public.qurbani_products(season_id);
create index if not exists qurbani_products_campaign_idx on public.qurbani_products(campaign_id);
create index if not exists qurbani_products_funding_pool_idx on public.qurbani_products(funding_pool_id);
create index if not exists qurbani_products_image_idx on public.qurbani_products(image_id);
create index if not exists qurbani_products_kind_idx on public.qurbani_products(kind);
create index if not exists qurbani_products_active_sort_idx on public.qurbani_products(season_id, sort_order, id) where is_active;
create index if not exists qurbani_products_updated_at_idx on public.qurbani_products(updated_at);
create unique index if not exists qurbani_products_locales_parent_locale_idx on public.qurbani_products_locales(_parent_id, _locale);

create unique index if not exists qurbani_pools_code_idx on public.qurbani_pools(code);
create index if not exists qurbani_pools_season_idx on public.qurbani_pools(season_id);
create index if not exists qurbani_pools_product_idx on public.qurbani_pools(product_id);
create index if not exists qurbani_pools_field_task_idx on public.qurbani_pools(field_task_id);
create unique index if not exists qurbani_pools_unique_field_task_idx on public.qurbani_pools(field_task_id) where field_task_id is not null;
create index if not exists qurbani_pools_open_capacity_idx on public.qurbani_pools(product_id, id) where status = 'open' and locked_at is null;
create index if not exists qurbani_pools_action_required_idx on public.qurbani_pools(updated_at) where action_required;
create index if not exists qurbani_pools_updated_at_idx on public.qurbani_pools(updated_at);

create unique index if not exists qurbani_orders_order_number_idx on public.qurbani_orders(order_number);
create index if not exists qurbani_orders_season_idx on public.qurbani_orders(season_id);
create index if not exists qurbani_orders_product_idx on public.qurbani_orders(product_id);
create index if not exists qurbani_orders_pool_idx on public.qurbani_orders(pool_id);
create index if not exists qurbani_orders_donation_intent_idx on public.qurbani_orders(donation_intent_id);
create index if not exists qurbani_orders_donation_idx on public.qurbani_orders(donation_id);
create index if not exists qurbani_orders_eft_reviewed_by_idx on public.qurbani_orders(eft_reviewed_by_id);
create index if not exists qurbani_orders_phone_proxy_confirmed_by_idx on public.qurbani_orders(phone_proxy_confirmed_by_id);
create index if not exists qurbani_orders_status_reservation_idx on public.qurbani_orders(status, reserved_until);
create index if not exists qurbani_orders_eft_review_idx on public.qurbani_orders(created_at) where status = 'pending_eft_review';
create unique index if not exists qurbani_orders_provider_payment_idx on public.qurbani_orders(provider_payment_id) where provider_payment_id is not null;
create index if not exists qurbani_orders_updated_at_idx on public.qurbani_orders(updated_at);

create unique index if not exists qurbani_shares_order_sequence_idx on public.qurbani_shares(order_id, sequence);
create index if not exists qurbani_shares_order_idx on public.qurbani_shares(order_id);
create index if not exists qurbani_shares_pool_status_idx on public.qurbani_shares(pool_id, status);
create index if not exists qurbani_shares_effective_phone_idx on public.qurbani_shares(effective_phone);
create index if not exists qurbani_shares_updated_at_idx on public.qurbani_shares(updated_at);

create unique index if not exists qurbani_videos_upload_id_idx on public.qurbani_videos(upload_id);
create index if not exists qurbani_videos_pool_idx on public.qurbani_videos(pool_id);
create index if not exists qurbani_videos_field_task_idx on public.qurbani_videos(field_task_id);
create index if not exists qurbani_videos_uploaded_by_idx on public.qurbani_videos(uploaded_by_id);
create index if not exists qurbani_videos_approved_by_idx on public.qurbani_videos(approved_by_id);
create index if not exists qurbani_videos_status_updated_idx on public.qurbani_videos(status, updated_at);
create index if not exists qurbani_videos_raw_retention_idx on public.qurbani_videos(raw_delete_after) where raw_storage_key is not null;
create index if not exists qurbani_videos_processed_retention_idx on public.qurbani_videos(processed_delete_after) where processed_storage_key is not null;

create unique index if not exists qurbani_access_links_token_digest_idx on public.qurbani_access_links(token_digest);
create index if not exists qurbani_access_links_pool_idx on public.qurbani_access_links(pool_id);
create index if not exists qurbani_access_links_order_idx on public.qurbani_access_links(order_id);
create index if not exists qurbani_access_links_video_idx on public.qurbani_access_links(video_id);
create index if not exists qurbani_access_links_phone_hash_idx on public.qurbani_access_links(recipient_phone_hash);
create index if not exists qurbani_access_links_active_idx on public.qurbani_access_links(expires_at) where revoked_at is null;
create index if not exists qurbani_access_links_rels_parent_idx on public.qurbani_access_links_rels(parent_id);
create index if not exists qurbani_access_links_rels_order_idx on public.qurbani_access_links_rels("order");
create index if not exists qurbani_access_links_rels_path_idx on public.qurbani_access_links_rels(path);
create index if not exists qurbani_access_links_rels_share_idx on public.qurbani_access_links_rels(qurbani_shares_id);

create unique index if not exists qurbani_messages_idempotency_key_idx on public.qurbani_messages(idempotency_key);
create unique index if not exists qurbani_messages_provider_message_idx on public.qurbani_messages(provider_message_id) where provider_message_id is not null;
create index if not exists qurbani_messages_pool_idx on public.qurbani_messages(pool_id);
create index if not exists qurbani_messages_access_link_idx on public.qurbani_messages(access_link_id);
create index if not exists qurbani_messages_phone_hash_idx on public.qurbani_messages(recipient_phone_hash);
create index if not exists qurbani_messages_queue_idx on public.qurbani_messages(status, updated_at) where status in ('queued', 'failed');

create unique index if not exists qurbani_jobs_idempotency_key_idx on public.qurbani_jobs(idempotency_key) where idempotency_key is not null;
create index if not exists qurbani_jobs_order_idx on public.qurbani_jobs(order_id);
create index if not exists qurbani_jobs_pool_idx on public.qurbani_jobs(pool_id);
create index if not exists qurbani_jobs_video_idx on public.qurbani_jobs(video_id);
create index if not exists qurbani_jobs_message_idx on public.qurbani_jobs(message_id);
create index if not exists qurbani_jobs_claim_idx on public.qurbani_jobs(run_at, id) where status in ('queued', 'failed');

create index if not exists donation_intents_qurbani_order_idx on public.donation_intents(qurbani_order_id);
create index if not exists donations_qurbani_order_idx on public.donations(qurbani_order_id);
create index if not exists field_tasks_qurbani_pool_idx on public.field_tasks(qurbani_pool_id);
create unique index if not exists field_tasks_unique_qurbani_pool_idx on public.field_tasks(qurbani_pool_id) where qurbani_pool_id is not null;

create sequence if not exists private.qurbani_order_number_seq;

create or replace function private.qurbani_refresh_pool_counters(p_pool_id integer)
returns void
language plpgsql
security invoker
set search_path = pg_catalog, public, private
as $$
declare
  v_reserved numeric;
  v_confirmed numeric;
  v_capacity numeric;
  v_status public.enum_qurbani_pools_status;
  v_locked_at timestamptz;
begin
  select capacity, status, locked_at
    into v_capacity, v_status, v_locked_at
  from public.qurbani_pools
  where id = p_pool_id
  for update;

  if not found then
    raise exception 'Qurbani pool % not found', p_pool_id;
  end if;

  select
    coalesce(sum(share_count) filter (
      where status in ('reserved', 'pending_payment', 'pending_eft_review') and reserved_until > now()
    ), 0),
    coalesce(sum(share_count) filter (where status = 'paid'), 0)
  into v_reserved, v_confirmed
  from public.qurbani_orders
  where pool_id = p_pool_id;

  if v_reserved + v_confirmed > v_capacity then
    raise exception 'Pool % capacity exceeded', p_pool_id;
  end if;

  update public.qurbani_pools
  set reserved_count = v_reserved,
      confirmed_count = v_confirmed,
      status = case
        when v_confirmed = v_capacity and status = 'open' then 'full'::public.enum_qurbani_pools_status
        when v_confirmed < v_capacity and status = 'full' and v_locked_at is null then 'open'::public.enum_qurbani_pools_status
        else status
      end,
      full_at = case when v_confirmed = v_capacity then coalesce(full_at, now()) else full_at end,
      updated_at = now()
  where id = p_pool_id;
end;
$$;

create or replace function private.qurbani_finalize_pool_code(p_pool_id integer)
returns character varying
language plpgsql
security invoker
set search_path = pg_catalog, public, private
as $$
declare
  v_season_id integer;
  v_year integer;
  v_counter integer;
  v_code character varying;
  v_capacity integer;
  v_confirmed integer;
begin
  select p.season_id, p.capacity::integer, p.confirmed_count::integer, p.code
    into v_season_id, v_capacity, v_confirmed, v_code
  from public.qurbani_pools p
  where p.id = p_pool_id
  for update;

  if not found then raise exception 'Qurbani pool % not found', p_pool_id; end if;
  if v_confirmed <> v_capacity then return v_code; end if;
  if v_code is not null then return v_code; end if;

  update public.qurbani_seasons
  set code_counter = code_counter + 1, updated_at = now()
  where id = v_season_id
  returning year::integer, code_counter::integer into v_year, v_counter;

  if v_counter > 9999 then raise exception 'Qurbani code capacity exhausted for season %', v_year; end if;
  v_code := format('MD-%s-%s', v_year, lpad(v_counter::text, 4, '0'));

  update public.qurbani_pools
  set code = v_code,
      status = case when status = 'open' then 'full'::public.enum_qurbani_pools_status else status end,
      full_at = coalesce(full_at, now()),
      updated_at = now()
  where id = p_pool_id;

  return v_code;
end;
$$;

create or replace function private.qurbani_reserve_order(p_order jsonb)
returns table (
  order_id integer,
  pool_id integer,
  reserved_until timestamp with time zone,
  total_amount numeric,
  currency text
)
language plpgsql
security invoker
set search_path = pg_catalog, public, private
as $$
declare
  v_product public.qurbani_products%rowtype;
  v_season public.qurbani_seasons%rowtype;
  v_pool_id integer;
  v_order_id integer;
  v_share_count integer;
  v_reserved_until timestamptz;
  v_order_number text;
  v_payment_method public.enum_qurbani_orders_payment_method;
  v_order_status public.enum_qurbani_orders_status;
  v_buyer_name text := btrim(coalesce(p_order->>'buyerName', ''));
  v_buyer_email text := btrim(coalesce(p_order->>'buyerEmail', ''));
  v_buyer_phone text := btrim(coalesce(p_order->>'buyerPhone', ''));
  v_has_owner_phone boolean;
begin
  if jsonb_typeof(p_order) <> 'object' or jsonb_typeof(p_order->'shares') <> 'array' then
    raise exception 'Invalid qurbani order payload';
  end if;
  if v_buyer_name = '' or v_buyer_email = '' or v_buyer_phone = '' then
    raise exception 'Buyer name, email and phone are required';
  end if;
  if not (coalesce((p_order->>'proxyAccepted')::boolean, false) or p_order ? 'proxyAcceptedAt') then
    raise exception 'Digital proxy acceptance is required';
  end if;
  if not (coalesce((p_order->>'kvkkAccepted')::boolean, false) or p_order ? 'kvkkAcceptedAt') then
    raise exception 'KVKK acceptance is required';
  end if;
  if not (coalesce((p_order->>'termsAccepted')::boolean, false) or p_order ? 'termsAcceptedAt') then
    raise exception 'Terms acceptance is required';
  end if;

  v_share_count := jsonb_array_length(p_order->'shares');
  if v_share_count < 1 or v_share_count > 7 then raise exception 'Share count must be between 1 and 7'; end if;
  if exists (
    select 1 from jsonb_array_elements(p_order->'shares') share
    where btrim(coalesce(share->>'ownerName', '')) = ''
  ) then
    raise exception 'Every share owner name is required';
  end if;

  select exists (
    select 1 from jsonb_array_elements(p_order->'shares') share
    where btrim(coalesce(share->>'ownerPhone', '')) <> ''
  ) into v_has_owner_phone;
  if v_has_owner_phone and not (
    coalesce((p_order->>'thirdPartyContactConsent')::boolean, false)
    or p_order ? 'thirdPartyContactConsentAt'
  ) then
    raise exception 'Third-party contact consent is required';
  end if;

  select * into v_product
  from public.qurbani_products
  where id = (p_order->>'productId')::integer
  for update;
  if not found then raise exception 'Qurbani product not found'; end if;

  select * into v_season
  from public.qurbani_seasons
  where id = v_product.season_id
  for update;

  if not v_product.is_active or v_season.status <> 'active' then
    raise exception 'Qurbani product is not on sale';
  end if;
  if now() < coalesce(v_product.sales_start_at, v_season.sales_start_at)
    or now() > coalesce(v_product.sales_end_at, v_season.sales_end_at) then
    raise exception 'Qurbani sales window is closed';
  end if;
  if v_share_count > v_product.capacity then
    raise exception 'The complete order does not fit in one animal pool';
  end if;

  begin
    v_payment_method := (p_order->>'paymentMethod')::public.enum_qurbani_orders_payment_method;
  exception when invalid_text_representation then
    raise exception 'Unsupported payment method';
  end;
  if v_payment_method is null then raise exception 'Payment method is required'; end if;

  v_reserved_until := now() + case when v_payment_method = 'iyzico' then interval '30 minutes' else interval '24 hours' end;
  v_order_status := case when v_payment_method = 'iyzico'
    then 'pending_payment'::public.enum_qurbani_orders_status
    else 'pending_eft_review'::public.enum_qurbani_orders_status end;

  select p.id into v_pool_id
  from public.qurbani_pools p
  where p.product_id = v_product.id
    and p.season_id = v_product.season_id
    and p.status = 'open'
    and p.locked_at is null
    and p.confirmed_count + p.reserved_count + v_share_count <= p.capacity
  order by p.id
  for update skip locked
  limit 1;

  if v_pool_id is null then
    insert into public.qurbani_pools (
      season_id, product_id, capacity, reserved_count, confirmed_count, status, updated_at, created_at
    ) values (
      v_product.season_id, v_product.id, v_product.capacity, 0, 0, 'open', now(), now()
    ) returning id into v_pool_id;
  end if;

  v_order_number := format(
    'KB-%s-%s',
    v_season.year::integer,
    lpad(nextval('private.qurbani_order_number_seq')::text, 8, '0')
  );

  insert into public.qurbani_orders (
    order_number, season_id, product_id, pool_id,
    buyer_name, buyer_email, buyer_phone, country_code, identity_type, identity_number,
    address_snapshot, product_snapshot, unit_price, share_count, total_amount, currency,
    payment_method, reservation_kind, status, reserved_until,
    proxy_text_version, proxy_accepted_at, proxy_accepted_ip,
    kvkk_accepted_at, terms_accepted_at, third_party_contact_consent_at,
    updated_at, created_at
  ) values (
    v_order_number, v_product.season_id, v_product.id, v_pool_id,
    v_buyer_name, v_buyer_email, v_buyer_phone,
    upper(coalesce(nullif(p_order->>'countryCode', ''), 'TR')),
    nullif(p_order->>'identityType', '')::public.enum_qurbani_orders_identity_type,
    nullif(btrim(p_order->>'identityNumber'), ''),
    coalesce(p_order->'addressSnapshot', '{}'::jsonb),
    jsonb_build_object(
      'productId', v_product.id, 'seasonId', v_product.season_id, 'kind', v_product.kind,
      'unitPrice', v_product.price, 'currency', v_product.currency, 'capacity', v_product.capacity
    ),
    v_product.price, v_share_count, v_product.price * v_share_count, v_product.currency::text::public.enum_qurbani_orders_currency,
    v_payment_method, v_payment_method::text::public.enum_qurbani_orders_reservation_kind, v_order_status, v_reserved_until,
    coalesce(nullif(p_order->>'proxyTextVersion', ''), v_season.proxy_text_version),
    now(), coalesce(nullif(p_order->>'ipAddress', ''), 'unknown'),
    now(), now(), case when v_has_owner_phone then now() else null end,
    now(), now()
  ) returning id into v_order_id;

  insert into public.qurbani_shares (
    order_id, pool_id, owner_name, owner_phone, effective_phone, sequence, status, updated_at, created_at
  )
  select
    v_order_id,
    v_pool_id,
    btrim(share.value->>'ownerName'),
    nullif(btrim(share.value->>'ownerPhone'), ''),
    coalesce(nullif(btrim(share.value->>'ownerPhone'), ''), v_buyer_phone),
    share.ordinality,
    'reserved'::public.enum_qurbani_shares_status,
    now(), now()
  from jsonb_array_elements(p_order->'shares') with ordinality as share(value, ordinality);

  update public.qurbani_pools
  set reserved_count = reserved_count + v_share_count, updated_at = now()
  where id = v_pool_id;

  insert into public.audit_logs(action, target_collection, target_id, details, ip_address, updated_at, created_at)
  values (
    'qurbani.order_reserved', 'qurbani-orders', v_order_id::text,
    jsonb_build_object('poolId', v_pool_id, 'shareCount', v_share_count, 'paymentMethod', v_payment_method),
    nullif(p_order->>'ipAddress', ''), now(), now()
  );

  return query select v_order_id, v_pool_id, v_reserved_until, v_product.price * v_share_count, v_product.currency::text;
end;
$$;

create or replace function private.qurbani_confirm_order_payment(
  p_order_id integer,
  p_donation_id integer default null,
  p_provider_id text default null,
  p_actor text default 'system'
)
returns table (pool_id integer, pool_code text, already_confirmed boolean)
language plpgsql
security invoker
set search_path = pg_catalog, public, private
as $$
declare
  v_order public.qurbani_orders%rowtype;
  v_product public.qurbani_products%rowtype;
  v_target_pool_id integer;
  v_source_pool_id integer;
  v_code text;
  v_pool record;
begin
  select * into v_order from public.qurbani_orders where id = p_order_id for update;
  if not found then raise exception 'Qurbani order % not found', p_order_id; end if;
  if v_order.status = 'paid' then
    select code into v_code from public.qurbani_pools where id = v_order.pool_id;
    return query select v_order.pool_id, v_code, true;
    return;
  end if;
  if v_order.status in ('cancelled', 'refunded', 'failed', 'action_required') then
    raise exception 'Qurbani order % cannot be confirmed from status %', p_order_id, v_order.status;
  end if;
  if p_provider_id is not null and exists (
    select 1 from public.qurbani_orders where provider_payment_id = p_provider_id and id <> p_order_id
  ) then
    raise exception 'Provider payment id is already bound to another qurbani order';
  end if;

  select * into v_product from public.qurbani_products where id = v_order.product_id for update;
  v_source_pool_id := v_order.pool_id;

  for v_pool in
    select id from public.qurbani_pools where product_id = v_order.product_id order by id for update
  loop
    perform private.qurbani_refresh_pool_counters(v_pool.id);
  end loop;

  select p.id into v_target_pool_id
  from public.qurbani_pools p
  where p.product_id = v_order.product_id
    and p.season_id = v_order.season_id
    and p.status = 'open'
    and p.locked_at is null
    and p.confirmed_count + p.reserved_count + v_order.share_count
      - case
          when p.id = v_source_pool_id
            and v_order.status in ('reserved', 'pending_payment', 'pending_eft_review')
            and v_order.reserved_until > now()
          then v_order.share_count
          else 0
        end <= p.capacity
  order by (p.id = v_source_pool_id) desc, p.id
  limit 1;

  if v_target_pool_id is null then
    insert into public.qurbani_pools(season_id, product_id, capacity, reserved_count, confirmed_count, status, updated_at, created_at)
    values(v_order.season_id, v_order.product_id, v_product.capacity, 0, 0, 'open', now(), now())
    returning id into v_target_pool_id;
  end if;

  update public.qurbani_orders
  set pool_id = v_target_pool_id,
      donation_id = coalesce(p_donation_id, donation_id),
      provider_payment_id = coalesce(nullif(p_provider_id, ''), provider_payment_id),
      provider_reference = coalesce(nullif(p_provider_id, ''), provider_reference),
      status = 'paid', paid_at = coalesce(paid_at, now()), failure_reason = null, updated_at = now()
  where id = p_order_id;

  update public.qurbani_shares
  set pool_id = v_target_pool_id, status = 'confirmed', confirmed_at = coalesce(confirmed_at, now()), updated_at = now()
  where order_id = p_order_id;

  if p_donation_id is not null then
    update public.donations set qurbani_order_id = p_order_id, updated_at = now() where id = p_donation_id;
  end if;

  if v_source_pool_id is not null and v_source_pool_id <> v_target_pool_id then
    perform private.qurbani_refresh_pool_counters(v_source_pool_id);
  end if;
  perform private.qurbani_refresh_pool_counters(v_target_pool_id);
  v_code := private.qurbani_finalize_pool_code(v_target_pool_id);

  insert into public.audit_logs(action, actor_email, target_collection, target_id, details, updated_at, created_at)
  values (
    'qurbani.order_payment_confirmed', nullif(p_actor, ''), 'qurbani-orders', p_order_id::text,
    jsonb_build_object('sourcePoolId', v_source_pool_id, 'poolId', v_target_pool_id, 'donationId', p_donation_id, 'providerId', p_provider_id),
    now(), now()
  );

  return query select v_target_pool_id, v_code, false;
end;
$$;

create or replace function private.qurbani_expire_reservations()
returns integer
language plpgsql
security invoker
set search_path = pg_catalog, public, private
as $$
declare
  v_order_ids integer[];
  v_pool_ids integer[];
  v_pool_id integer;
  v_count integer := 0;
begin
  with candidates as (
    select id, pool_id
    from public.qurbani_orders
    where status in ('reserved', 'pending_payment', 'pending_eft_review')
      and reserved_until <= now()
    order by reserved_until, id
    for update skip locked
    limit 500
  )
  select array_agg(id), array_agg(distinct pool_id)
    into v_order_ids, v_pool_ids
  from candidates;

  if v_order_ids is null then return 0; end if;
  v_count := cardinality(v_order_ids);

  update public.qurbani_orders
  set status = 'expired', failure_reason = coalesce(failure_reason, 'reservation_expired'), updated_at = now()
  where id = any(v_order_ids);

  update public.qurbani_shares
  set status = 'cancelled', updated_at = now()
  where order_id = any(v_order_ids) and status = 'reserved';

  foreach v_pool_id in array v_pool_ids loop
    if v_pool_id is not null then perform private.qurbani_refresh_pool_counters(v_pool_id); end if;
  end loop;

  insert into public.audit_logs(action, actor_email, target_collection, details, updated_at, created_at)
  values ('qurbani.reservations_expired', 'worker', 'qurbani-orders', jsonb_build_object('count', v_count, 'orderIds', v_order_ids), now(), now());
  return v_count;
end;
$$;

create or replace function private.qurbani_transfer_order(
  p_order_id integer,
  p_target_pool_id integer,
  p_actor_id integer
)
returns table (source_pool_id integer, target_pool_id integer, target_pool_code text)
language plpgsql
security invoker
set search_path = pg_catalog, public, private
as $$
declare
  v_order public.qurbani_orders%rowtype;
  v_source public.qurbani_pools%rowtype;
  v_target public.qurbani_pools%rowtype;
  v_actor_email text;
  v_code text;
  v_lock record;
begin
  select * into v_order from public.qurbani_orders where id = p_order_id for update;
  if not found or v_order.pool_id is null then raise exception 'Qurbani order or source pool not found'; end if;
  if v_order.pool_id = p_target_pool_id then raise exception 'Source and target pool must be different'; end if;
  if v_order.status not in ('reserved', 'pending_payment', 'pending_eft_review', 'paid') then
    raise exception 'Qurbani order % cannot be transferred from status %', p_order_id, v_order.status;
  end if;
  if v_order.status <> 'paid' and v_order.reserved_until <= now() then raise exception 'Reservation has expired'; end if;

  perform 1 from public.qurbani_products where id = v_order.product_id for update;
  for v_lock in
    select id from public.qurbani_pools where id in (v_order.pool_id, p_target_pool_id) order by id for update
  loop null; end loop;

  select * into v_source from public.qurbani_pools where id = v_order.pool_id;
  select * into v_target from public.qurbani_pools where id = p_target_pool_id;
  if not found then raise exception 'Target pool not found'; end if;
  if v_source.locked_at is not null or v_source.status in ('in_progress', 'video_processing', 'ready', 'notified', 'closed') then
    raise exception 'Source pool is locked because field work has started';
  end if;
  if v_target.locked_at is not null or v_target.status <> 'open' then raise exception 'Target pool must be open and unlocked'; end if;
  if v_target.product_id <> v_source.product_id or v_target.season_id <> v_source.season_id then
    raise exception 'Pools must belong to the same season and product';
  end if;

  perform private.qurbani_refresh_pool_counters(v_source.id);
  perform private.qurbani_refresh_pool_counters(v_target.id);
  select * into v_target from public.qurbani_pools where id = p_target_pool_id;
  if v_target.confirmed_count + v_target.reserved_count + v_order.share_count > v_target.capacity then
    raise exception 'Target pool does not have enough capacity for the complete order';
  end if;

  update public.qurbani_orders set pool_id = p_target_pool_id, updated_at = now() where id = p_order_id;
  update public.qurbani_shares set pool_id = p_target_pool_id, updated_at = now() where order_id = p_order_id;
  perform private.qurbani_refresh_pool_counters(v_source.id);
  perform private.qurbani_refresh_pool_counters(v_target.id);
  if v_order.status = 'paid' then v_code := private.qurbani_finalize_pool_code(v_target.id); end if;

  select email into v_actor_email from public.users where id = p_actor_id;
  insert into public.audit_logs(action, actor_email, target_collection, target_id, details, updated_at, created_at)
  values (
    'qurbani.order_transferred', v_actor_email, 'qurbani-orders', p_order_id::text,
    jsonb_build_object('sourcePoolId', v_source.id, 'targetPoolId', v_target.id, 'actorId', p_actor_id), now(), now()
  );

  return query select v_source.id, v_target.id, v_code;
end;
$$;

do $$
declare
  relation record;
begin
  for relation in
    select * from (values
      ('qurbani_seasons_id', 'qurbani_seasons'),
      ('qurbani_products_id', 'qurbani_products'),
      ('qurbani_orders_id', 'qurbani_orders'),
      ('qurbani_shares_id', 'qurbani_shares'),
      ('qurbani_pools_id', 'qurbani_pools'),
      ('qurbani_videos_id', 'qurbani_videos'),
      ('qurbani_access_links_id', 'qurbani_access_links'),
      ('qurbani_messages_id', 'qurbani_messages'),
      ('qurbani_jobs_id', 'qurbani_jobs')
    ) as rel(column_name, table_name)
  loop
    execute format(
      'alter table public.payload_locked_documents_rels add column if not exists %I integer',
      relation.column_name
    );
    if not exists (
      select 1 from pg_constraint
      where conname = format('payload_locked_documents_rels_%s_fk', relation.column_name)
    ) then
      execute format(
        'alter table public.payload_locked_documents_rels add constraint %I foreign key (%I) references public.%I(id) on delete cascade',
        format('payload_locked_documents_rels_%s_fk', relation.column_name),
        relation.column_name,
        relation.table_name
      );
    end if;
    execute format(
      'create index if not exists %I on public.payload_locked_documents_rels(%I)',
      format('payload_locked_documents_rels_%s_idx', relation.column_name),
      relation.column_name
    );
  end loop;
end;
$$;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values (
  'qurbani-eft-proofs',
  'qurbani-eft-proofs',
  false,
  10485760,
  array['application/pdf', 'image/jpeg', 'image/png']::text[]
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'qurbani_seasons', 'qurbani_seasons_locales',
    'qurbani_products', 'qurbani_products_locales',
    'qurbani_pools', 'qurbani_orders', 'qurbani_shares', 'qurbani_videos',
    'qurbani_access_links', 'qurbani_access_links_rels', 'qurbani_messages', 'qurbani_jobs'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on public.%I from anon, authenticated', table_name);
    if exists (select 1 from pg_roles where rolname = 'service_role') then
      execute format('grant select, insert, update, delete on public.%I to service_role', table_name);
    end if;
  end loop;
end;
$$;

revoke all on function private.qurbani_refresh_pool_counters(integer) from public;
revoke all on function private.qurbani_finalize_pool_code(integer) from public;
revoke all on function private.qurbani_reserve_order(jsonb) from public;
revoke all on function private.qurbani_confirm_order_payment(integer, integer, text, text) from public;
revoke all on function private.qurbani_expire_reservations() from public;
revoke all on function private.qurbani_transfer_order(integer, integer, integer) from public;
revoke all on schema private from public, anon, authenticated;

do $$
declare
  sequence_name text;
begin
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    grant usage on schema private to service_role;
    grant usage, select on sequence private.qurbani_order_number_seq to service_role;
    for sequence_name in
      select pg_get_serial_sequence(format('public.%I', table_name), 'id')
      from unnest(array[
        'qurbani_seasons', 'qurbani_seasons_locales',
        'qurbani_products', 'qurbani_products_locales',
        'qurbani_pools', 'qurbani_orders', 'qurbani_shares', 'qurbani_videos',
        'qurbani_access_links', 'qurbani_access_links_rels', 'qurbani_messages', 'qurbani_jobs'
      ]) table_name
    loop
      execute format('grant usage, select on sequence %s to service_role', sequence_name);
    end loop;
    grant execute on function private.qurbani_refresh_pool_counters(integer) to service_role;
    grant execute on function private.qurbani_finalize_pool_code(integer) to service_role;
    grant execute on function private.qurbani_reserve_order(jsonb) to service_role;
    grant execute on function private.qurbani_confirm_order_payment(integer, integer, text, text) to service_role;
    grant execute on function private.qurbani_expire_reservations() to service_role;
    grant execute on function private.qurbani_transfer_order(integer, integer, integer) to service_role;
  end if;
end;
$$;

commit;
